// Code generated by ent, DO NOT EDIT.

package accountbalancebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldAccountID, v))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldSiteID, v))
}

// ExternalKeyID applies equality check predicate on the "external_key_id" field. It's identical to ExternalKeyIDEQ.
func ExternalKeyID(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldExternalKeyID, v))
}

// KeyLast4 applies equality check predicate on the "key_last4" field. It's identical to KeyLast4EQ.
func KeyLast4(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldKeyLast4, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldAccountID, vs...))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...int64) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldSiteID, vs...))
}

// ExternalKeyIDEQ applies the EQ predicate on the "external_key_id" field.
func ExternalKeyIDEQ(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldExternalKeyID, v))
}

// ExternalKeyIDNEQ applies the NEQ predicate on the "external_key_id" field.
func ExternalKeyIDNEQ(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldExternalKeyID, v))
}

// ExternalKeyIDIn applies the In predicate on the "external_key_id" field.
func ExternalKeyIDIn(vs ...string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldExternalKeyID, vs...))
}

// ExternalKeyIDNotIn applies the NotIn predicate on the "external_key_id" field.
func ExternalKeyIDNotIn(vs ...string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldExternalKeyID, vs...))
}

// ExternalKeyIDGT applies the GT predicate on the "external_key_id" field.
func ExternalKeyIDGT(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGT(FieldExternalKeyID, v))
}

// ExternalKeyIDGTE applies the GTE predicate on the "external_key_id" field.
func ExternalKeyIDGTE(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGTE(FieldExternalKeyID, v))
}

// ExternalKeyIDLT applies the LT predicate on the "external_key_id" field.
func ExternalKeyIDLT(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLT(FieldExternalKeyID, v))
}

// ExternalKeyIDLTE applies the LTE predicate on the "external_key_id" field.
func ExternalKeyIDLTE(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLTE(FieldExternalKeyID, v))
}

// ExternalKeyIDContains applies the Contains predicate on the "external_key_id" field.
func ExternalKeyIDContains(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldContains(FieldExternalKeyID, v))
}

// ExternalKeyIDHasPrefix applies the HasPrefix predicate on the "external_key_id" field.
func ExternalKeyIDHasPrefix(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldHasPrefix(FieldExternalKeyID, v))
}

// ExternalKeyIDHasSuffix applies the HasSuffix predicate on the "external_key_id" field.
func ExternalKeyIDHasSuffix(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldHasSuffix(FieldExternalKeyID, v))
}

// ExternalKeyIDIsNil applies the IsNil predicate on the "external_key_id" field.
func ExternalKeyIDIsNil() predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIsNull(FieldExternalKeyID))
}

// ExternalKeyIDNotNil applies the NotNil predicate on the "external_key_id" field.
func ExternalKeyIDNotNil() predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotNull(FieldExternalKeyID))
}

// ExternalKeyIDEqualFold applies the EqualFold predicate on the "external_key_id" field.
func ExternalKeyIDEqualFold(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEqualFold(FieldExternalKeyID, v))
}

// ExternalKeyIDContainsFold applies the ContainsFold predicate on the "external_key_id" field.
func ExternalKeyIDContainsFold(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldContainsFold(FieldExternalKeyID, v))
}

// KeyLast4EQ applies the EQ predicate on the "key_last4" field.
func KeyLast4EQ(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldKeyLast4, v))
}

// KeyLast4NEQ applies the NEQ predicate on the "key_last4" field.
func KeyLast4NEQ(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldKeyLast4, v))
}

// KeyLast4In applies the In predicate on the "key_last4" field.
func KeyLast4In(vs ...string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldKeyLast4, vs...))
}

// KeyLast4NotIn applies the NotIn predicate on the "key_last4" field.
func KeyLast4NotIn(vs ...string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldKeyLast4, vs...))
}

// KeyLast4GT applies the GT predicate on the "key_last4" field.
func KeyLast4GT(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGT(FieldKeyLast4, v))
}

// KeyLast4GTE applies the GTE predicate on the "key_last4" field.
func KeyLast4GTE(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldGTE(FieldKeyLast4, v))
}

// KeyLast4LT applies the LT predicate on the "key_last4" field.
func KeyLast4LT(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLT(FieldKeyLast4, v))
}

// KeyLast4LTE applies the LTE predicate on the "key_last4" field.
func KeyLast4LTE(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldLTE(FieldKeyLast4, v))
}

// KeyLast4Contains applies the Contains predicate on the "key_last4" field.
func KeyLast4Contains(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldContains(FieldKeyLast4, v))
}

// KeyLast4HasPrefix applies the HasPrefix predicate on the "key_last4" field.
func KeyLast4HasPrefix(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldHasPrefix(FieldKeyLast4, v))
}

// KeyLast4HasSuffix applies the HasSuffix predicate on the "key_last4" field.
func KeyLast4HasSuffix(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldHasSuffix(FieldKeyLast4, v))
}

// KeyLast4EqualFold applies the EqualFold predicate on the "key_last4" field.
func KeyLast4EqualFold(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEqualFold(FieldKeyLast4, v))
}

// KeyLast4ContainsFold applies the ContainsFold predicate on the "key_last4" field.
func KeyLast4ContainsFold(v string) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldContainsFold(FieldKeyLast4, v))
}

// MatchModeEQ applies the EQ predicate on the "match_mode" field.
func MatchModeEQ(v MatchMode) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldEQ(FieldMatchMode, v))
}

// MatchModeNEQ applies the NEQ predicate on the "match_mode" field.
func MatchModeNEQ(v MatchMode) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNEQ(FieldMatchMode, v))
}

// MatchModeIn applies the In predicate on the "match_mode" field.
func MatchModeIn(vs ...MatchMode) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldIn(FieldMatchMode, vs...))
}

// MatchModeNotIn applies the NotIn predicate on the "match_mode" field.
func MatchModeNotIn(vs ...MatchMode) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.FieldNotIn(FieldMatchMode, vs...))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.BalanceSite) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountBalanceBinding) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountBalanceBinding) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountBalanceBinding) predicate.AccountBalanceBinding {
	return predicate.AccountBalanceBinding(sql.NotPredicates(p))
}
