// Code generated by ent, DO NOT EDIT.

package balancesite

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the balancesite type in the database.
	Label = "balance_site"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldAuthMode holds the string denoting the auth_mode field in the database.
	FieldAuthMode = "auth_mode"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordEncrypted holds the string denoting the password_encrypted field in the database.
	FieldPasswordEncrypted = "password_encrypted"
	// FieldAccessTokenEncrypted holds the string denoting the access_token_encrypted field in the database.
	FieldAccessTokenEncrypted = "access_token_encrypted"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRefreshIntervalMinutes holds the string denoting the refresh_interval_minutes field in the database.
	FieldRefreshIntervalMinutes = "refresh_interval_minutes"
	// FieldLastRefreshAt holds the string denoting the last_refresh_at field in the database.
	FieldLastRefreshAt = "last_refresh_at"
	// FieldLastRefreshStatus holds the string denoting the last_refresh_status field in the database.
	FieldLastRefreshStatus = "last_refresh_status"
	// FieldLastRefreshError holds the string denoting the last_refresh_error field in the database.
	FieldLastRefreshError = "last_refresh_error"
	// EdgeSnapshots holds the string denoting the snapshots edge name in mutations.
	EdgeSnapshots = "snapshots"
	// EdgeBindings holds the string denoting the bindings edge name in mutations.
	EdgeBindings = "bindings"
	// Table holds the table name of the balancesite in the database.
	Table = "balance_sites"
	// SnapshotsTable is the table that holds the snapshots relation/edge.
	SnapshotsTable = "balance_key_snapshots"
	// SnapshotsInverseTable is the table name for the BalanceKeySnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "balancekeysnapshot" package.
	SnapshotsInverseTable = "balance_key_snapshots"
	// SnapshotsColumn is the table column denoting the snapshots relation/edge.
	SnapshotsColumn = "site_id"
	// BindingsTable is the table that holds the bindings relation/edge.
	BindingsTable = "account_balance_bindings"
	// BindingsInverseTable is the table name for the AccountBalanceBinding entity.
	// It exists in this package in order to avoid circular dependency with the "accountbalancebinding" package.
	BindingsInverseTable = "account_balance_bindings"
	// BindingsColumn is the table column denoting the bindings relation/edge.
	BindingsColumn = "site_id"
)

// Columns holds all SQL columns for balancesite fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPlatform,
	FieldName,
	FieldBaseURL,
	FieldAuthMode,
	FieldUsername,
	FieldEmail,
	FieldPasswordEncrypted,
	FieldAccessTokenEncrypted,
	FieldEnabled,
	FieldRefreshIntervalMinutes,
	FieldLastRefreshAt,
	FieldLastRefreshStatus,
	FieldLastRefreshError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultPasswordEncrypted holds the default value on creation for the "password_encrypted" field.
	DefaultPasswordEncrypted string
	// DefaultAccessTokenEncrypted holds the default value on creation for the "access_token_encrypted" field.
	DefaultAccessTokenEncrypted string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultRefreshIntervalMinutes holds the default value on creation for the "refresh_interval_minutes" field.
	DefaultRefreshIntervalMinutes int
	// RefreshIntervalMinutesValidator is a validator for the "refresh_interval_minutes" field. It is called by the builders before save.
	RefreshIntervalMinutesValidator func(int) error
	// DefaultLastRefreshStatus holds the default value on creation for the "last_refresh_status" field.
	DefaultLastRefreshStatus string
	// LastRefreshStatusValidator is a validator for the "last_refresh_status" field. It is called by the builders before save.
	LastRefreshStatusValidator func(string) error
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformNewapi  Platform = "newapi"
	PlatformSub2api Platform = "sub2api"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformNewapi, PlatformSub2api:
		return nil
	default:
		return fmt.Errorf("balancesite: invalid enum value for platform field: %q", pl)
	}
}

// AuthMode defines the type for the "auth_mode" enum field.
type AuthMode string

// AuthModePassword is the default value of the AuthMode enum.
const DefaultAuthMode = AuthModePassword

// AuthMode values.
const (
	AuthModePassword    AuthMode = "password"
	AuthModeAccessToken AuthMode = "access_token"
)

func (am AuthMode) String() string {
	return string(am)
}

// AuthModeValidator is a validator for the "auth_mode" field enum values. It is called by the builders before save.
func AuthModeValidator(am AuthMode) error {
	switch am {
	case AuthModePassword, AuthModeAccessToken:
		return nil
	default:
		return fmt.Errorf("balancesite: invalid enum value for auth_mode field: %q", am)
	}
}

// OrderOption defines the ordering options for the BalanceSite queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByAuthMode orders the results by the auth_mode field.
func ByAuthMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMode, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordEncrypted orders the results by the password_encrypted field.
func ByPasswordEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordEncrypted, opts...).ToFunc()
}

// ByAccessTokenEncrypted orders the results by the access_token_encrypted field.
func ByAccessTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenEncrypted, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRefreshIntervalMinutes orders the results by the refresh_interval_minutes field.
func ByRefreshIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshIntervalMinutes, opts...).ToFunc()
}

// ByLastRefreshAt orders the results by the last_refresh_at field.
func ByLastRefreshAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshAt, opts...).ToFunc()
}

// ByLastRefreshStatus orders the results by the last_refresh_status field.
func ByLastRefreshStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshStatus, opts...).ToFunc()
}

// ByLastRefreshError orders the results by the last_refresh_error field.
func ByLastRefreshError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshError, opts...).ToFunc()
}

// BySnapshotsCount orders the results by snapshots count.
func BySnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSnapshotsStep(), opts...)
	}
}

// BySnapshots orders the results by snapshots terms.
func BySnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBindingsCount orders the results by bindings count.
func ByBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBindingsStep(), opts...)
	}
}

// ByBindings orders the results by bindings terms.
func ByBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
	)
}
func newBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
	)
}
