// Code generated by ent, DO NOT EDIT.

package balancesite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldBaseURL, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldUsername, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldEmail, v))
}

// PasswordEncrypted applies equality check predicate on the "password_encrypted" field. It's identical to PasswordEncryptedEQ.
func PasswordEncrypted(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldEnabled, v))
}

// RefreshIntervalMinutes applies equality check predicate on the "refresh_interval_minutes" field. It's identical to RefreshIntervalMinutesEQ.
func RefreshIntervalMinutes(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// LastRefreshAt applies equality check predicate on the "last_refresh_at" field. It's identical to LastRefreshAtEQ.
func LastRefreshAt(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshStatus applies equality check predicate on the "last_refresh_status" field. It's identical to LastRefreshStatusEQ.
func LastRefreshStatus(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshStatus, v))
}

// LastRefreshError applies equality check predicate on the "last_refresh_error" field. It's identical to LastRefreshErrorEQ.
func LastRefreshError(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldUpdatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v Platform) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v Platform) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...Platform) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...Platform) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldPlatform, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldBaseURL, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldUsername, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEncryptedEQ applies the EQ predicate on the "password_encrypted" field.
func PasswordEncryptedEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedNEQ applies the NEQ predicate on the "password_encrypted" field.
func PasswordEncryptedNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIn applies the In predicate on the "password_encrypted" field.
func PasswordEncryptedIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedNotIn applies the NotIn predicate on the "password_encrypted" field.
func PasswordEncryptedNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedGT applies the GT predicate on the "password_encrypted" field.
func PasswordEncryptedGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedGTE applies the GTE predicate on the "password_encrypted" field.
func PasswordEncryptedGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLT applies the LT predicate on the "password_encrypted" field.
func PasswordEncryptedLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLTE applies the LTE predicate on the "password_encrypted" field.
func PasswordEncryptedLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContains applies the Contains predicate on the "password_encrypted" field.
func PasswordEncryptedContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasPrefix applies the HasPrefix predicate on the "password_encrypted" field.
func PasswordEncryptedHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasSuffix applies the HasSuffix predicate on the "password_encrypted" field.
func PasswordEncryptedHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedEqualFold applies the EqualFold predicate on the "password_encrypted" field.
func PasswordEncryptedEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContainsFold applies the ContainsFold predicate on the "password_encrypted" field.
func PasswordEncryptedContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldPasswordEncrypted, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldEnabled, v))
}

// RefreshIntervalMinutesEQ applies the EQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesEQ(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesNEQ applies the NEQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNEQ(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesIn applies the In predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesIn(vs ...int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesNotIn applies the NotIn predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNotIn(vs ...int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesGT applies the GT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGT(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesGTE applies the GTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGTE(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLT applies the LT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLT(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLTE applies the LTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLTE(v int) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldRefreshIntervalMinutes, v))
}

// LastRefreshAtEQ applies the EQ predicate on the "last_refresh_at" field.
func LastRefreshAtEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtNEQ applies the NEQ predicate on the "last_refresh_at" field.
func LastRefreshAtNEQ(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtIn applies the In predicate on the "last_refresh_at" field.
func LastRefreshAtIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtNotIn applies the NotIn predicate on the "last_refresh_at" field.
func LastRefreshAtNotIn(vs ...time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtGT applies the GT predicate on the "last_refresh_at" field.
func LastRefreshAtGT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldLastRefreshAt, v))
}

// LastRefreshAtGTE applies the GTE predicate on the "last_refresh_at" field.
func LastRefreshAtGTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldLastRefreshAt, v))
}

// LastRefreshAtLT applies the LT predicate on the "last_refresh_at" field.
func LastRefreshAtLT(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldLastRefreshAt, v))
}

// LastRefreshAtLTE applies the LTE predicate on the "last_refresh_at" field.
func LastRefreshAtLTE(v time.Time) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldLastRefreshAt, v))
}

// LastRefreshAtIsNil applies the IsNil predicate on the "last_refresh_at" field.
func LastRefreshAtIsNil() predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIsNull(FieldLastRefreshAt))
}

// LastRefreshAtNotNil applies the NotNil predicate on the "last_refresh_at" field.
func LastRefreshAtNotNil() predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotNull(FieldLastRefreshAt))
}

// LastRefreshStatusEQ applies the EQ predicate on the "last_refresh_status" field.
func LastRefreshStatusEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshStatus, v))
}

// LastRefreshStatusNEQ applies the NEQ predicate on the "last_refresh_status" field.
func LastRefreshStatusNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldLastRefreshStatus, v))
}

// LastRefreshStatusIn applies the In predicate on the "last_refresh_status" field.
func LastRefreshStatusIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldLastRefreshStatus, vs...))
}

// LastRefreshStatusNotIn applies the NotIn predicate on the "last_refresh_status" field.
func LastRefreshStatusNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldLastRefreshStatus, vs...))
}

// LastRefreshStatusGT applies the GT predicate on the "last_refresh_status" field.
func LastRefreshStatusGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldLastRefreshStatus, v))
}

// LastRefreshStatusGTE applies the GTE predicate on the "last_refresh_status" field.
func LastRefreshStatusGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldLastRefreshStatus, v))
}

// LastRefreshStatusLT applies the LT predicate on the "last_refresh_status" field.
func LastRefreshStatusLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldLastRefreshStatus, v))
}

// LastRefreshStatusLTE applies the LTE predicate on the "last_refresh_status" field.
func LastRefreshStatusLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldLastRefreshStatus, v))
}

// LastRefreshStatusContains applies the Contains predicate on the "last_refresh_status" field.
func LastRefreshStatusContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldLastRefreshStatus, v))
}

// LastRefreshStatusHasPrefix applies the HasPrefix predicate on the "last_refresh_status" field.
func LastRefreshStatusHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldLastRefreshStatus, v))
}

// LastRefreshStatusHasSuffix applies the HasSuffix predicate on the "last_refresh_status" field.
func LastRefreshStatusHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldLastRefreshStatus, v))
}

// LastRefreshStatusEqualFold applies the EqualFold predicate on the "last_refresh_status" field.
func LastRefreshStatusEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldLastRefreshStatus, v))
}

// LastRefreshStatusContainsFold applies the ContainsFold predicate on the "last_refresh_status" field.
func LastRefreshStatusContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldLastRefreshStatus, v))
}

// LastRefreshErrorEQ applies the EQ predicate on the "last_refresh_error" field.
func LastRefreshErrorEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorNEQ applies the NEQ predicate on the "last_refresh_error" field.
func LastRefreshErrorNEQ(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorIn applies the In predicate on the "last_refresh_error" field.
func LastRefreshErrorIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorNotIn applies the NotIn predicate on the "last_refresh_error" field.
func LastRefreshErrorNotIn(vs ...string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorGT applies the GT predicate on the "last_refresh_error" field.
func LastRefreshErrorGT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGT(FieldLastRefreshError, v))
}

// LastRefreshErrorGTE applies the GTE predicate on the "last_refresh_error" field.
func LastRefreshErrorGTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldGTE(FieldLastRefreshError, v))
}

// LastRefreshErrorLT applies the LT predicate on the "last_refresh_error" field.
func LastRefreshErrorLT(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLT(FieldLastRefreshError, v))
}

// LastRefreshErrorLTE applies the LTE predicate on the "last_refresh_error" field.
func LastRefreshErrorLTE(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldLTE(FieldLastRefreshError, v))
}

// LastRefreshErrorContains applies the Contains predicate on the "last_refresh_error" field.
func LastRefreshErrorContains(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContains(FieldLastRefreshError, v))
}

// LastRefreshErrorHasPrefix applies the HasPrefix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasPrefix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasPrefix(FieldLastRefreshError, v))
}

// LastRefreshErrorHasSuffix applies the HasSuffix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasSuffix(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldHasSuffix(FieldLastRefreshError, v))
}

// LastRefreshErrorIsNil applies the IsNil predicate on the "last_refresh_error" field.
func LastRefreshErrorIsNil() predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldIsNull(FieldLastRefreshError))
}

// LastRefreshErrorNotNil applies the NotNil predicate on the "last_refresh_error" field.
func LastRefreshErrorNotNil() predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldNotNull(FieldLastRefreshError))
}

// LastRefreshErrorEqualFold applies the EqualFold predicate on the "last_refresh_error" field.
func LastRefreshErrorEqualFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldEqualFold(FieldLastRefreshError, v))
}

// LastRefreshErrorContainsFold applies the ContainsFold predicate on the "last_refresh_error" field.
func LastRefreshErrorContainsFold(v string) predicate.BalanceSite {
	return predicate.BalanceSite(sql.FieldContainsFold(FieldLastRefreshError, v))
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.BalanceSite {
	return predicate.BalanceSite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.BalanceKeySnapshot) predicate.BalanceSite {
	return predicate.BalanceSite(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.BalanceSite {
	return predicate.BalanceSite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.AccountBalanceBinding) predicate.BalanceSite {
	return predicate.BalanceSite(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceSite) predicate.BalanceSite {
	return predicate.BalanceSite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceSite) predicate.BalanceSite {
	return predicate.BalanceSite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceSite) predicate.BalanceSite {
	return predicate.BalanceSite(sql.NotPredicates(p))
}
