ALTER TABLE account_quality_snapshots
ADD COLUMN IF NOT EXISTS ttft_gt_10s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ttft_gt_20s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ttft_gt_40s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ttft_gt_10s_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ttft_gt_20s_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ttft_gt_40s_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS failure_requests BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS error_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS sample_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS fast_bonus DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS slow_penalty DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS error_penalty DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS neutral_base DOUBLE PRECISION NOT NULL DEFAULT 0;
