ALTER TABLE account_quality_snapshots
ADD COLUMN IF NOT EXISTS auxiliary_total_requests BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_success_requests BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_failure_requests BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_sample_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_le_5s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_le_10s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_gt_10s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_gt_20s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_ttft_gt_40s_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS auxiliary_weight DOUBLE PRECISION NOT NULL DEFAULT 0;
