ALTER TABLE account_quality_snapshots
ADD COLUMN IF NOT EXISTS base_quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS effective_quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS transient_penalty DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recovery_credit DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS slow_streak BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS error_streak BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recovery_success_streak BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recovery_fast_streak BIGINT NOT NULL DEFAULT 0;
