// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorrate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUpstreamMonitorRateDelete is the builder for deleting a AccountUpstreamMonitorRate entity.
type AccountUpstreamMonitorRateDelete struct {
	config
	hooks    []Hook
	mutation *AccountUpstreamMonitorRateMutation
}

// Where appends a list predicates to the AccountUpstreamMonitorRateDelete builder.
func (_d *AccountUpstreamMonitorRateDelete) Where(ps ...predicate.AccountUpstreamMonitorRate) *AccountUpstreamMonitorRateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountUpstreamMonitorRateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUpstreamMonitorRateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountUpstreamMonitorRateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountupstreammonitorrate.Table, sqlgraph.NewFieldSpec(accountupstreammonitorrate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountUpstreamMonitorRateDeleteOne is the builder for deleting a single AccountUpstreamMonitorRate entity.
type AccountUpstreamMonitorRateDeleteOne struct {
	_d *AccountUpstreamMonitorRateDelete
}

// Where appends a list predicates to the AccountUpstreamMonitorRateDelete builder.
func (_d *AccountUpstreamMonitorRateDeleteOne) Where(ps ...predicate.AccountUpstreamMonitorRate) *AccountUpstreamMonitorRateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountUpstreamMonitorRateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountupstreammonitorrate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUpstreamMonitorRateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
