// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorrate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUpstreamMonitorRateUpdate is the builder for updating AccountUpstreamMonitorRate entities.
type AccountUpstreamMonitorRateUpdate struct {
	config
	hooks    []Hook
	mutation *AccountUpstreamMonitorRateMutation
}

// Where appends a list predicates to the AccountUpstreamMonitorRateUpdate builder.
func (_u *AccountUpstreamMonitorRateUpdate) Where(ps ...predicate.AccountUpstreamMonitorRate) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetAccountID(v int64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableAccountID(v *int64) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountUpstreamMonitorRateUpdate) AddAccountID(v int64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableProvider(v *accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetRateKey sets the "rate_key" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetRateKey(v string) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetRateKey(v)
	return _u
}

// SetNillableRateKey sets the "rate_key" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableRateKey(v *string) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetRateKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetDisplayName(v string) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableDisplayName(v *string) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetDescription(v string) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableDescription(v *string) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountUpstreamMonitorRateUpdate) ClearDescription() *AccountUpstreamMonitorRateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRatio sets the "ratio" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetRatio(v float64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.ResetRatio()
	_u.mutation.SetRatio(v)
	return _u
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableRatio(v *float64) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetRatio(*v)
	}
	return _u
}

// AddRatio adds value to the "ratio" field.
func (_u *AccountUpstreamMonitorRateUpdate) AddRatio(v float64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.AddRatio(v)
	return _u
}

// SetCompletionRatio sets the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.ResetCompletionRatio()
	_u.mutation.SetCompletionRatio(v)
	return _u
}

// SetNillableCompletionRatio sets the "completion_ratio" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableCompletionRatio(v *float64) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetCompletionRatio(*v)
	}
	return _u
}

// AddCompletionRatio adds value to the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdate) AddCompletionRatio(v float64) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.AddCompletionRatio(v)
	return _u
}

// ClearCompletionRatio clears the value of the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdate) ClearCompletionRatio() *AccountUpstreamMonitorRateUpdate {
	_u.mutation.ClearCompletionRatio()
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableFirstSeenAt(v *time.Time) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AccountUpstreamMonitorRateUpdate) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdate) SetNillableLastSeenAt(v *time.Time) *AccountUpstreamMonitorRateUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the AccountUpstreamMonitorRateMutation object of the builder.
func (_u *AccountUpstreamMonitorRateUpdate) Mutation() *AccountUpstreamMonitorRateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpstreamMonitorRateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamMonitorRateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpstreamMonitorRateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamMonitorRateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamMonitorRateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamMonitorRateUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountupstreammonitorrate.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateKey(); ok {
		if err := accountupstreammonitorrate.RateKeyValidator(v); err != nil {
			return &ValidationError{Name: "rate_key", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.rate_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := accountupstreammonitorrate.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := accountupstreammonitorrate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamMonitorRateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreammonitorrate.Table, accountupstreammonitorrate.Columns, sqlgraph.NewFieldSpec(accountupstreammonitorrate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RateKey(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountupstreammonitorrate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Ratio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatio(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CompletionRatio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompletionRatio(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64, value)
	}
	if _u.mutation.CompletionRatioCleared() {
		_spec.ClearField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldLastSeenAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreammonitorrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpstreamMonitorRateUpdateOne is the builder for updating a single AccountUpstreamMonitorRate entity.
type AccountUpstreamMonitorRateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountUpstreamMonitorRateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetAccountID(v int64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableAccountID(v *int64) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) AddAccountID(v int64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableProvider(v *accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetRateKey sets the "rate_key" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetRateKey(v string) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetRateKey(v)
	return _u
}

// SetNillableRateKey sets the "rate_key" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableRateKey(v *string) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetRateKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetDisplayName(v string) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableDisplayName(v *string) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetDescription(v string) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableDescription(v *string) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) ClearDescription() *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRatio sets the "ratio" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetRatio(v float64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.ResetRatio()
	_u.mutation.SetRatio(v)
	return _u
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableRatio(v *float64) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetRatio(*v)
	}
	return _u
}

// AddRatio adds value to the "ratio" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) AddRatio(v float64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.AddRatio(v)
	return _u
}

// SetCompletionRatio sets the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.ResetCompletionRatio()
	_u.mutation.SetCompletionRatio(v)
	return _u
}

// SetNillableCompletionRatio sets the "completion_ratio" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableCompletionRatio(v *float64) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetCompletionRatio(*v)
	}
	return _u
}

// AddCompletionRatio adds value to the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) AddCompletionRatio(v float64) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.AddCompletionRatio(v)
	return _u
}

// ClearCompletionRatio clears the value of the "completion_ratio" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) ClearCompletionRatio() *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.ClearCompletionRatio()
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableFirstSeenAt(v *time.Time) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorRateUpdateOne) SetNillableLastSeenAt(v *time.Time) *AccountUpstreamMonitorRateUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the AccountUpstreamMonitorRateMutation object of the builder.
func (_u *AccountUpstreamMonitorRateUpdateOne) Mutation() *AccountUpstreamMonitorRateMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpstreamMonitorRateUpdate builder.
func (_u *AccountUpstreamMonitorRateUpdateOne) Where(ps ...predicate.AccountUpstreamMonitorRate) *AccountUpstreamMonitorRateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpstreamMonitorRateUpdateOne) Select(field string, fields ...string) *AccountUpstreamMonitorRateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountUpstreamMonitorRate entity.
func (_u *AccountUpstreamMonitorRateUpdateOne) Save(ctx context.Context) (*AccountUpstreamMonitorRate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamMonitorRateUpdateOne) SaveX(ctx context.Context) *AccountUpstreamMonitorRate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpstreamMonitorRateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamMonitorRateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamMonitorRateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamMonitorRateUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountupstreammonitorrate.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateKey(); ok {
		if err := accountupstreammonitorrate.RateKeyValidator(v); err != nil {
			return &ValidationError{Name: "rate_key", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.rate_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := accountupstreammonitorrate.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := accountupstreammonitorrate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.description": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamMonitorRateUpdateOne) sqlSave(ctx context.Context) (_node *AccountUpstreamMonitorRate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreammonitorrate.Table, accountupstreammonitorrate.Columns, sqlgraph.NewFieldSpec(accountupstreammonitorrate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountUpstreamMonitorRate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountupstreammonitorrate.FieldID)
		for _, f := range fields {
			if !accountupstreammonitorrate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountupstreammonitorrate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RateKey(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountupstreammonitorrate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Ratio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatio(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CompletionRatio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompletionRatio(); ok {
		_spec.AddField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64, value)
	}
	if _u.mutation.CompletionRatioCleared() {
		_spec.ClearField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldLastSeenAt, field.TypeTime, value)
	}
	_node = &AccountUpstreamMonitorRate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreammonitorrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
