// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountbalancebinding"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
)

// AccountBalanceBinding is the model entity for the AccountBalanceBinding schema.
type AccountBalanceBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID int64 `json:"site_id,omitempty"`
	// ExternalKeyID holds the value of the "external_key_id" field.
	ExternalKeyID *string `json:"external_key_id,omitempty"`
	// KeyLast4 holds the value of the "key_last4" field.
	KeyLast4 string `json:"key_last4,omitempty"`
	// MatchMode holds the value of the "match_mode" field.
	MatchMode accountbalancebinding.MatchMode `json:"match_mode,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountBalanceBindingQuery when eager-loading is set.
	Edges        AccountBalanceBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountBalanceBindingEdges holds the relations/edges for other nodes in the graph.
type AccountBalanceBindingEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Site holds the value of the site edge.
	Site *BalanceSite `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountBalanceBindingEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountBalanceBindingEdges) SiteOrErr() (*BalanceSite, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: balancesite.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountBalanceBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountbalancebinding.FieldID, accountbalancebinding.FieldAccountID, accountbalancebinding.FieldSiteID:
			values[i] = new(sql.NullInt64)
		case accountbalancebinding.FieldExternalKeyID, accountbalancebinding.FieldKeyLast4, accountbalancebinding.FieldMatchMode:
			values[i] = new(sql.NullString)
		case accountbalancebinding.FieldCreatedAt, accountbalancebinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountBalanceBinding fields.
func (_m *AccountBalanceBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountbalancebinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountbalancebinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountbalancebinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountbalancebinding.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountbalancebinding.FieldSiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteID = value.Int64
			}
		case accountbalancebinding.FieldExternalKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_key_id", values[i])
			} else if value.Valid {
				_m.ExternalKeyID = new(string)
				*_m.ExternalKeyID = value.String
			}
		case accountbalancebinding.FieldKeyLast4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_last4", values[i])
			} else if value.Valid {
				_m.KeyLast4 = value.String
			}
		case accountbalancebinding.FieldMatchMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_mode", values[i])
			} else if value.Valid {
				_m.MatchMode = accountbalancebinding.MatchMode(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountBalanceBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AccountBalanceBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountBalanceBinding entity.
func (_m *AccountBalanceBinding) QueryAccount() *AccountQuery {
	return NewAccountBalanceBindingClient(_m.config).QueryAccount(_m)
}

// QuerySite queries the "site" edge of the AccountBalanceBinding entity.
func (_m *AccountBalanceBinding) QuerySite() *BalanceSiteQuery {
	return NewAccountBalanceBindingClient(_m.config).QuerySite(_m)
}

// Update returns a builder for updating this AccountBalanceBinding.
// Note that you need to call AccountBalanceBinding.Unwrap() before calling this method if this AccountBalanceBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountBalanceBinding) Update() *AccountBalanceBindingUpdateOne {
	return NewAccountBalanceBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountBalanceBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountBalanceBinding) Unwrap() *AccountBalanceBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountBalanceBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountBalanceBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AccountBalanceBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SiteID))
	builder.WriteString(", ")
	if v := _m.ExternalKeyID; v != nil {
		builder.WriteString("external_key_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("key_last4=")
	builder.WriteString(_m.KeyLast4)
	builder.WriteString(", ")
	builder.WriteString("match_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchMode))
	builder.WriteByte(')')
	return builder.String()
}

// AccountBalanceBindings is a parsable slice of AccountBalanceBinding.
type AccountBalanceBindings []*AccountBalanceBinding
