// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUpstreamMonitorSnapshotUpdate is the builder for updating AccountUpstreamMonitorSnapshot entities.
type AccountUpstreamMonitorSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *AccountUpstreamMonitorSnapshotMutation
}

// Where appends a list predicates to the AccountUpstreamMonitorSnapshotUpdate builder.
func (_u *AccountUpstreamMonitorSnapshotUpdate) Where(ps ...predicate.AccountUpstreamMonitorSnapshot) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableAccountID(v *int64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddAccountID(v int64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableProvider(v *accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableStatus(v *accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSiteURL sets the "site_url" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetSiteURL(v)
	return _u
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableSiteURL(v *string) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetSiteURL(*v)
	}
	return _u
}

// ClearSiteURL clears the value of the "site_url" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearSiteURL() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearSiteURL()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetBalance(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableBalance(v *float64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddBalance(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearBalance() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearBalance()
	return _u
}

// SetBalanceUnit sets the "balance_unit" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetBalanceUnit(v)
	return _u
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableBalanceUnit(v *string) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetBalanceUnit(*v)
	}
	return _u
}

// ClearBalanceUnit clears the value of the "balance_unit" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearBalanceUnit() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearBalanceUnit()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetQuota(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableQuota(v *float64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddQuota(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearQuota() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearQuota()
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableQuotaUsed(v *float64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// ClearQuotaUsed clears the value of the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearQuotaUsed() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearQuotaUsed()
	return _u
}

// SetTodayCost sets the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetTodayCost()
	_u.mutation.SetTodayCost(v)
	return _u
}

// SetNillableTodayCost sets the "today_cost" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableTodayCost(v *float64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetTodayCost(*v)
	}
	return _u
}

// AddTodayCost adds value to the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddTodayCost(v)
	return _u
}

// ClearTodayCost clears the value of the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearTodayCost() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearTodayCost()
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableTotalCost(v *float64) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) AddTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// ClearTotalCost clears the value of the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearTotalCost() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearTotalCost()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableLastCheckedAt(v *time.Time) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearLastCheckedAt() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableLastSuccessAt(v *time.Time) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearLastSuccessAt() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetLastError(v string) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetNillableLastError(v *string) *AccountUpstreamMonitorSnapshotUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ClearLastError() *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetRawMeta sets the "raw_meta" field.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotUpdate {
	_u.mutation.SetRawMeta(v)
	return _u
}

// Mutation returns the AccountUpstreamMonitorSnapshotMutation object of the builder.
func (_u *AccountUpstreamMonitorSnapshotUpdate) Mutation() *AccountUpstreamMonitorSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpstreamMonitorSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamMonitorSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpstreamMonitorSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamMonitorSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamMonitorSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamMonitorSnapshotUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountupstreammonitorsnapshot.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountupstreammonitorsnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteURL(); ok {
		if err := accountupstreammonitorsnapshot.SiteURLValidator(v); err != nil {
			return &ValidationError{Name: "site_url", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.site_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceUnit(); ok {
		if err := accountupstreammonitorsnapshot.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.balance_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamMonitorSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreammonitorsnapshot.Table, accountupstreammonitorsnapshot.Columns, sqlgraph.NewFieldSpec(accountupstreammonitorsnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SiteURL(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldSiteURL, field.TypeString, value)
	}
	if _u.mutation.SiteURLCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldSiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceUnit(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalanceUnit, field.TypeString, value)
	}
	if _u.mutation.BalanceUnitCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldBalanceUnit, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaUsedCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCost(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64, value)
	}
	if _u.mutation.TodayCostCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64, value)
	}
	if _u.mutation.TotalCostCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.RawMeta(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldRawMeta, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreammonitorsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpstreamMonitorSnapshotUpdateOne is the builder for updating a single AccountUpstreamMonitorSnapshot entity.
type AccountUpstreamMonitorSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountUpstreamMonitorSnapshotMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableAccountID(v *int64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddAccountID(v int64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableProvider(v *accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableStatus(v *accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSiteURL sets the "site_url" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetSiteURL(v)
	return _u
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableSiteURL(v *string) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetSiteURL(*v)
	}
	return _u
}

// ClearSiteURL clears the value of the "site_url" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearSiteURL() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearSiteURL()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetBalance(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableBalance(v *float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddBalance(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearBalance() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearBalance()
	return _u
}

// SetBalanceUnit sets the "balance_unit" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetBalanceUnit(v)
	return _u
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableBalanceUnit(v *string) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetBalanceUnit(*v)
	}
	return _u
}

// ClearBalanceUnit clears the value of the "balance_unit" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearBalanceUnit() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearBalanceUnit()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetQuota(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableQuota(v *float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddQuota(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearQuota() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearQuota()
	return _u
}

// SetQuotaUsed sets the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetQuotaUsed()
	_u.mutation.SetQuotaUsed(v)
	return _u
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableQuotaUsed(v *float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetQuotaUsed(*v)
	}
	return _u
}

// AddQuotaUsed adds value to the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddQuotaUsed(v)
	return _u
}

// ClearQuotaUsed clears the value of the "quota_used" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearQuotaUsed() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearQuotaUsed()
	return _u
}

// SetTodayCost sets the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetTodayCost()
	_u.mutation.SetTodayCost(v)
	return _u
}

// SetNillableTodayCost sets the "today_cost" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableTodayCost(v *float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetTodayCost(*v)
	}
	return _u
}

// AddTodayCost adds value to the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddTodayCost(v)
	return _u
}

// ClearTodayCost clears the value of the "today_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearTodayCost() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearTodayCost()
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableTotalCost(v *float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) AddTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// ClearTotalCost clears the value of the "total_cost" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearTotalCost() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearTotalCost()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableLastCheckedAt(v *time.Time) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearLastCheckedAt() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableLastSuccessAt(v *time.Time) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearLastSuccessAt() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetLastError(v string) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetNillableLastError(v *string) *AccountUpstreamMonitorSnapshotUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ClearLastError() *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetRawMeta sets the "raw_meta" field.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.SetRawMeta(v)
	return _u
}

// Mutation returns the AccountUpstreamMonitorSnapshotMutation object of the builder.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) Mutation() *AccountUpstreamMonitorSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpstreamMonitorSnapshotUpdate builder.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) Where(ps ...predicate.AccountUpstreamMonitorSnapshot) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) Select(field string, fields ...string) *AccountUpstreamMonitorSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountUpstreamMonitorSnapshot entity.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) Save(ctx context.Context) (*AccountUpstreamMonitorSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) SaveX(ctx context.Context) *AccountUpstreamMonitorSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorsnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpstreamMonitorSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := accountupstreammonitorsnapshot.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := accountupstreammonitorsnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteURL(); ok {
		if err := accountupstreammonitorsnapshot.SiteURLValidator(v); err != nil {
			return &ValidationError{Name: "site_url", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.site_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceUnit(); ok {
		if err := accountupstreammonitorsnapshot.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.balance_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpstreamMonitorSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *AccountUpstreamMonitorSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountupstreammonitorsnapshot.Table, accountupstreammonitorsnapshot.Columns, sqlgraph.NewFieldSpec(accountupstreammonitorsnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountUpstreamMonitorSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountupstreammonitorsnapshot.FieldID)
		for _, f := range fields {
			if !accountupstreammonitorsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountupstreammonitorsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SiteURL(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldSiteURL, field.TypeString, value)
	}
	if _u.mutation.SiteURLCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldSiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceUnit(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalanceUnit, field.TypeString, value)
	}
	if _u.mutation.BalanceUnitCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldBalanceUnit, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuotaUsed(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsed(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64, value)
	}
	if _u.mutation.QuotaUsedCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCost(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64, value)
	}
	if _u.mutation.TodayCostCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64, value)
	}
	if _u.mutation.TotalCostCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(accountupstreammonitorsnapshot.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.RawMeta(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldRawMeta, field.TypeJSON, value)
	}
	_node = &AccountUpstreamMonitorSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountupstreammonitorsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
