// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorrate"
)

// AccountUpstreamMonitorRate is the model entity for the AccountUpstreamMonitorRate schema.
type AccountUpstreamMonitorRate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider accountupstreammonitorrate.Provider `json:"provider,omitempty"`
	// RateKey holds the value of the "rate_key" field.
	RateKey string `json:"rate_key,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Ratio holds the value of the "ratio" field.
	Ratio float64 `json:"ratio,omitempty"`
	// CompletionRatio holds the value of the "completion_ratio" field.
	CompletionRatio *float64 `json:"completion_ratio,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt   time.Time `json:"last_seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountUpstreamMonitorRate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountupstreammonitorrate.FieldRatio, accountupstreammonitorrate.FieldCompletionRatio:
			values[i] = new(sql.NullFloat64)
		case accountupstreammonitorrate.FieldID, accountupstreammonitorrate.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case accountupstreammonitorrate.FieldProvider, accountupstreammonitorrate.FieldRateKey, accountupstreammonitorrate.FieldDisplayName, accountupstreammonitorrate.FieldDescription:
			values[i] = new(sql.NullString)
		case accountupstreammonitorrate.FieldCreatedAt, accountupstreammonitorrate.FieldUpdatedAt, accountupstreammonitorrate.FieldFirstSeenAt, accountupstreammonitorrate.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountUpstreamMonitorRate fields.
func (_m *AccountUpstreamMonitorRate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountupstreammonitorrate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountupstreammonitorrate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountupstreammonitorrate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountupstreammonitorrate.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountupstreammonitorrate.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = accountupstreammonitorrate.Provider(value.String)
			}
		case accountupstreammonitorrate.FieldRateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate_key", values[i])
			} else if value.Valid {
				_m.RateKey = value.String
			}
		case accountupstreammonitorrate.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case accountupstreammonitorrate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case accountupstreammonitorrate.FieldRatio:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ratio", values[i])
			} else if value.Valid {
				_m.Ratio = value.Float64
			}
		case accountupstreammonitorrate.FieldCompletionRatio:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_ratio", values[i])
			} else if value.Valid {
				_m.CompletionRatio = new(float64)
				*_m.CompletionRatio = value.Float64
			}
		case accountupstreammonitorrate.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = value.Time
			}
		case accountupstreammonitorrate.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountUpstreamMonitorRate.
// This includes values selected through modifiers, order, etc.
func (_m *AccountUpstreamMonitorRate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountUpstreamMonitorRate.
// Note that you need to call AccountUpstreamMonitorRate.Unwrap() before calling this method if this AccountUpstreamMonitorRate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountUpstreamMonitorRate) Update() *AccountUpstreamMonitorRateUpdateOne {
	return NewAccountUpstreamMonitorRateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountUpstreamMonitorRate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountUpstreamMonitorRate) Unwrap() *AccountUpstreamMonitorRate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountUpstreamMonitorRate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountUpstreamMonitorRate) String() string {
	var builder strings.Builder
	builder.WriteString("AccountUpstreamMonitorRate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("rate_key=")
	builder.WriteString(_m.RateKey)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ratio))
	builder.WriteString(", ")
	if v := _m.CompletionRatio; v != nil {
		builder.WriteString("completion_ratio=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(_m.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountUpstreamMonitorRates is a parsable slice of AccountUpstreamMonitorRate.
type AccountUpstreamMonitorRates []*AccountUpstreamMonitorRate
