// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorsnapshot"
)

// AccountUpstreamMonitorSnapshotCreate is the builder for creating a AccountUpstreamMonitorSnapshot entity.
type AccountUpstreamMonitorSnapshotCreate struct {
	config
	mutation *AccountUpstreamMonitorSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetCreatedAt(v time.Time) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableCreatedAt(v *time.Time) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableProvider(v *accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableStatus(v *accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSiteURL sets the "site_url" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetSiteURL(v)
	return _c
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableSiteURL(v *string) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetSiteURL(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetBalance(v float64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableBalance(v *float64) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetBalanceUnit sets the "balance_unit" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetBalanceUnit(v)
	return _c
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableBalanceUnit(v *string) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetBalanceUnit(*v)
	}
	return _c
}

// SetQuota sets the "quota" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetQuota(v float64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetQuota(v)
	return _c
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableQuota(v *float64) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetQuota(*v)
	}
	return _c
}

// SetQuotaUsed sets the "quota_used" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetQuotaUsed(v)
	return _c
}

// SetNillableQuotaUsed sets the "quota_used" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableQuotaUsed(v *float64) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetQuotaUsed(*v)
	}
	return _c
}

// SetTodayCost sets the "today_cost" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetTodayCost(v)
	return _c
}

// SetNillableTodayCost sets the "today_cost" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableTodayCost(v *float64) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetTodayCost(*v)
	}
	return _c
}

// SetTotalCost sets the "total_cost" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetTotalCost(v)
	return _c
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableTotalCost(v *float64) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetTotalCost(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableLastCheckedAt(v *time.Time) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableLastSuccessAt(v *time.Time) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetLastError(v string) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetNillableLastError(v *string) *AccountUpstreamMonitorSnapshotCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetRawMeta sets the "raw_meta" field.
func (_c *AccountUpstreamMonitorSnapshotCreate) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotCreate {
	_c.mutation.SetRawMeta(v)
	return _c
}

// Mutation returns the AccountUpstreamMonitorSnapshotMutation object of the builder.
func (_c *AccountUpstreamMonitorSnapshotCreate) Mutation() *AccountUpstreamMonitorSnapshotMutation {
	return _c.mutation
}

// Save creates the AccountUpstreamMonitorSnapshot in the database.
func (_c *AccountUpstreamMonitorSnapshotCreate) Save(ctx context.Context) (*AccountUpstreamMonitorSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUpstreamMonitorSnapshotCreate) SaveX(ctx context.Context) *AccountUpstreamMonitorSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamMonitorSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamMonitorSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUpstreamMonitorSnapshotCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountupstreammonitorsnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorsnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := accountupstreammonitorsnapshot.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := accountupstreammonitorsnapshot.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RawMeta(); !ok {
		v := accountupstreammonitorsnapshot.DefaultRawMeta()
		_c.mutation.SetRawMeta(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUpstreamMonitorSnapshotCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.account_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := accountupstreammonitorsnapshot.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := accountupstreammonitorsnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SiteURL(); ok {
		if err := accountupstreammonitorsnapshot.SiteURLValidator(v); err != nil {
			return &ValidationError{Name: "site_url", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.site_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BalanceUnit(); ok {
		if err := accountupstreammonitorsnapshot.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorSnapshot.balance_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RawMeta(); !ok {
		return &ValidationError{Name: "raw_meta", err: errors.New(`ent: missing required field "AccountUpstreamMonitorSnapshot.raw_meta"`)}
	}
	return nil
}

func (_c *AccountUpstreamMonitorSnapshotCreate) sqlSave(ctx context.Context) (*AccountUpstreamMonitorSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUpstreamMonitorSnapshotCreate) createSpec() (*AccountUpstreamMonitorSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUpstreamMonitorSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountupstreammonitorsnapshot.Table, sqlgraph.NewFieldSpec(accountupstreammonitorsnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SiteURL(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldSiteURL, field.TypeString, value)
		_node.SiteURL = &value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalance, field.TypeFloat64, value)
		_node.Balance = &value
	}
	if value, ok := _c.mutation.BalanceUnit(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldBalanceUnit, field.TypeString, value)
		_node.BalanceUnit = &value
	}
	if value, ok := _c.mutation.Quota(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuota, field.TypeFloat64, value)
		_node.Quota = &value
	}
	if value, ok := _c.mutation.QuotaUsed(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldQuotaUsed, field.TypeFloat64, value)
		_node.QuotaUsed = &value
	}
	if value, ok := _c.mutation.TodayCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTodayCost, field.TypeFloat64, value)
		_node.TodayCost = &value
	}
	if value, ok := _c.mutation.TotalCost(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldTotalCost, field.TypeFloat64, value)
		_node.TotalCost = &value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.RawMeta(); ok {
		_spec.SetField(accountupstreammonitorsnapshot.FieldRawMeta, field.TypeJSON, value)
		_node.RawMeta = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamMonitorSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamMonitorSnapshotUpsertOne {
	_c.conflict = opts
	return &AccountUpstreamMonitorSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorSnapshotCreate) OnConflictColumns(columns ...string) *AccountUpstreamMonitorSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamMonitorSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpstreamMonitorSnapshotUpsertOne is the builder for "upsert"-ing
	//  one AccountUpstreamMonitorSnapshot node.
	AccountUpstreamMonitorSnapshotUpsertOne struct {
		create *AccountUpstreamMonitorSnapshotCreate
	}

	// AccountUpstreamMonitorSnapshotUpsert is the "OnConflict" setter.
	AccountUpstreamMonitorSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateUpdatedAt() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateAccountID() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldAccountID, v)
	return u
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateProvider() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldProvider)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateStatus() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldStatus)
	return u
}

// SetSiteURL sets the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldSiteURL, v)
	return u
}

// UpdateSiteURL sets the "site_url" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateSiteURL() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldSiteURL)
	return u
}

// ClearSiteURL clears the value of the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearSiteURL() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldSiteURL)
	return u
}

// SetBalance sets the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetBalance(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateBalance() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddBalance(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldBalance, v)
	return u
}

// ClearBalance clears the value of the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearBalance() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldBalance)
	return u
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldBalanceUnit, v)
	return u
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateBalanceUnit() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldBalanceUnit)
	return u
}

// ClearBalanceUnit clears the value of the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearBalanceUnit() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldBalanceUnit)
	return u
}

// SetQuota sets the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetQuota(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldQuota, v)
	return u
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateQuota() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldQuota)
	return u
}

// AddQuota adds v to the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddQuota(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldQuota, v)
	return u
}

// ClearQuota clears the value of the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearQuota() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldQuota)
	return u
}

// SetQuotaUsed sets the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldQuotaUsed, v)
	return u
}

// UpdateQuotaUsed sets the "quota_used" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateQuotaUsed() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldQuotaUsed)
	return u
}

// AddQuotaUsed adds v to the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldQuotaUsed, v)
	return u
}

// ClearQuotaUsed clears the value of the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearQuotaUsed() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldQuotaUsed)
	return u
}

// SetTodayCost sets the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldTodayCost, v)
	return u
}

// UpdateTodayCost sets the "today_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateTodayCost() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldTodayCost)
	return u
}

// AddTodayCost adds v to the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldTodayCost, v)
	return u
}

// ClearTodayCost clears the value of the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearTodayCost() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldTodayCost)
	return u
}

// SetTotalCost sets the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldTotalCost, v)
	return u
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateTotalCost() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldTotalCost)
	return u
}

// AddTotalCost adds v to the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) AddTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsert {
	u.Add(accountupstreammonitorsnapshot.FieldTotalCost, v)
	return u
}

// ClearTotalCost clears the value of the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearTotalCost() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldTotalCost)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldLastCheckedAt)
	return u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldLastSuccessAt, v)
	return u
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldLastSuccessAt)
	return u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldLastSuccessAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetLastError(v string) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateLastError() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) ClearLastError() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetNull(accountupstreammonitorsnapshot.FieldLastError)
	return u
}

// SetRawMeta sets the "raw_meta" field.
func (u *AccountUpstreamMonitorSnapshotUpsert) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotUpsert {
	u.Set(accountupstreammonitorsnapshot.FieldRawMeta, v)
	return u
}

// UpdateRawMeta sets the "raw_meta" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsert) UpdateRawMeta() *AccountUpstreamMonitorSnapshotUpsert {
	u.SetExcluded(accountupstreammonitorsnapshot.FieldRawMeta)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateNewValues() *AccountUpstreamMonitorSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountupstreammonitorsnapshot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpstreamMonitorSnapshotUpsertOne) Ignore() *AccountUpstreamMonitorSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) DoNothing() *AccountUpstreamMonitorSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamMonitorSnapshotCreate.OnConflict
// documentation for more info.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) Update(set func(*AccountUpstreamMonitorSnapshotUpsert)) *AccountUpstreamMonitorSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamMonitorSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateUpdatedAt() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateAccountID() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateProvider() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateStatus() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetSiteURL sets the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetSiteURL(v)
	})
}

// UpdateSiteURL sets the "site_url" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateSiteURL() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateSiteURL()
	})
}

// ClearSiteURL clears the value of the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearSiteURL() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearSiteURL()
	})
}

// SetBalance sets the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetBalance(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddBalance(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateBalance() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateBalance()
	})
}

// ClearBalance clears the value of the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearBalance() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearBalance()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateBalanceUnit() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateBalanceUnit()
	})
}

// ClearBalanceUnit clears the value of the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearBalanceUnit() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearBalanceUnit()
	})
}

// SetQuota sets the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetQuota(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddQuota(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateQuota() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateQuota()
	})
}

// ClearQuota clears the value of the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearQuota() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearQuota()
	})
}

// SetQuotaUsed sets the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetQuotaUsed(v)
	})
}

// AddQuotaUsed adds v to the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddQuotaUsed(v)
	})
}

// UpdateQuotaUsed sets the "quota_used" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateQuotaUsed() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateQuotaUsed()
	})
}

// ClearQuotaUsed clears the value of the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearQuotaUsed() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearQuotaUsed()
	})
}

// SetTodayCost sets the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetTodayCost(v)
	})
}

// AddTodayCost adds v to the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddTodayCost(v)
	})
}

// UpdateTodayCost sets the "today_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateTodayCost() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateTodayCost()
	})
}

// ClearTodayCost clears the value of the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearTodayCost() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearTodayCost()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) AddTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateTotalCost() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateTotalCost()
	})
}

// ClearTotalCost clears the value of the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearTotalCost() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearTotalCost()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetLastError(v string) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateLastError() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ClearLastError() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastError()
	})
}

// SetRawMeta sets the "raw_meta" field.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetRawMeta(v)
	})
}

// UpdateRawMeta sets the "raw_meta" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) UpdateRawMeta() *AccountUpstreamMonitorSnapshotUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateRawMeta()
	})
}

// Exec executes the query.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamMonitorSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpstreamMonitorSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUpstreamMonitorSnapshotCreateBulk is the builder for creating many AccountUpstreamMonitorSnapshot entities in bulk.
type AccountUpstreamMonitorSnapshotCreateBulk struct {
	config
	err      error
	builders []*AccountUpstreamMonitorSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUpstreamMonitorSnapshot entities in the database.
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) Save(ctx context.Context) ([]*AccountUpstreamMonitorSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUpstreamMonitorSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUpstreamMonitorSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) SaveX(ctx context.Context) []*AccountUpstreamMonitorSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamMonitorSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamMonitorSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamMonitorSnapshotUpsertBulk {
	_c.conflict = opts
	return &AccountUpstreamMonitorSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorSnapshotCreateBulk) OnConflictColumns(columns ...string) *AccountUpstreamMonitorSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamMonitorSnapshotUpsertBulk{
		create: _c,
	}
}

// AccountUpstreamMonitorSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUpstreamMonitorSnapshot nodes.
type AccountUpstreamMonitorSnapshotUpsertBulk struct {
	create *AccountUpstreamMonitorSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateNewValues() *AccountUpstreamMonitorSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountupstreammonitorsnapshot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) Ignore() *AccountUpstreamMonitorSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) DoNothing() *AccountUpstreamMonitorSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamMonitorSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) Update(set func(*AccountUpstreamMonitorSnapshotUpsert)) *AccountUpstreamMonitorSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamMonitorSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateUpdatedAt() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddAccountID(v int64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateAccountID() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetProvider(v accountupstreammonitorsnapshot.Provider) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateProvider() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateProvider()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetStatus(v accountupstreammonitorsnapshot.Status) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateStatus() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetSiteURL sets the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetSiteURL(v string) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetSiteURL(v)
	})
}

// UpdateSiteURL sets the "site_url" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateSiteURL() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateSiteURL()
	})
}

// ClearSiteURL clears the value of the "site_url" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearSiteURL() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearSiteURL()
	})
}

// SetBalance sets the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetBalance(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddBalance(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateBalance() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateBalance()
	})
}

// ClearBalance clears the value of the "balance" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearBalance() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearBalance()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetBalanceUnit(v string) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateBalanceUnit() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateBalanceUnit()
	})
}

// ClearBalanceUnit clears the value of the "balance_unit" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearBalanceUnit() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearBalanceUnit()
	})
}

// SetQuota sets the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetQuota(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddQuota(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateQuota() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateQuota()
	})
}

// ClearQuota clears the value of the "quota" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearQuota() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearQuota()
	})
}

// SetQuotaUsed sets the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetQuotaUsed(v)
	})
}

// AddQuotaUsed adds v to the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddQuotaUsed(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddQuotaUsed(v)
	})
}

// UpdateQuotaUsed sets the "quota_used" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateQuotaUsed() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateQuotaUsed()
	})
}

// ClearQuotaUsed clears the value of the "quota_used" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearQuotaUsed() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearQuotaUsed()
	})
}

// SetTodayCost sets the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetTodayCost(v)
	})
}

// AddTodayCost adds v to the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddTodayCost(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddTodayCost(v)
	})
}

// UpdateTodayCost sets the "today_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateTodayCost() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateTodayCost()
	})
}

// ClearTodayCost clears the value of the "today_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearTodayCost() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearTodayCost()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) AddTotalCost(v float64) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateTotalCost() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateTotalCost()
	})
}

// ClearTotalCost clears the value of the "total_cost" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearTotalCost() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearTotalCost()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetLastCheckedAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearLastCheckedAt() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetLastSuccessAt(v time.Time) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearLastSuccessAt() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetLastError(v string) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateLastError() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ClearLastError() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.ClearLastError()
	})
}

// SetRawMeta sets the "raw_meta" field.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) SetRawMeta(v map[string]interface{}) *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.SetRawMeta(v)
	})
}

// UpdateRawMeta sets the "raw_meta" field to the value that was provided on create.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) UpdateRawMeta() *AccountUpstreamMonitorSnapshotUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorSnapshotUpsert) {
		s.UpdateRawMeta()
	})
}

// Exec executes the query.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUpstreamMonitorSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamMonitorSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamMonitorSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
