// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountupstreammonitorrate"
)

// AccountUpstreamMonitorRateCreate is the builder for creating a AccountUpstreamMonitorRate entity.
type AccountUpstreamMonitorRateCreate struct {
	config
	mutation *AccountUpstreamMonitorRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountUpstreamMonitorRateCreate) SetCreatedAt(v time.Time) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorRateCreate) SetNillableCreatedAt(v *time.Time) *AccountUpstreamMonitorRateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountUpstreamMonitorRateCreate) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountUpstreamMonitorRateCreate) SetNillableUpdatedAt(v *time.Time) *AccountUpstreamMonitorRateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountUpstreamMonitorRateCreate) SetAccountID(v int64) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AccountUpstreamMonitorRateCreate) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AccountUpstreamMonitorRateCreate) SetNillableProvider(v *accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetRateKey sets the "rate_key" field.
func (_c *AccountUpstreamMonitorRateCreate) SetRateKey(v string) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetRateKey(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AccountUpstreamMonitorRateCreate) SetDisplayName(v string) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AccountUpstreamMonitorRateCreate) SetDescription(v string) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AccountUpstreamMonitorRateCreate) SetNillableDescription(v *string) *AccountUpstreamMonitorRateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRatio sets the "ratio" field.
func (_c *AccountUpstreamMonitorRateCreate) SetRatio(v float64) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetRatio(v)
	return _c
}

// SetCompletionRatio sets the "completion_ratio" field.
func (_c *AccountUpstreamMonitorRateCreate) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetCompletionRatio(v)
	return _c
}

// SetNillableCompletionRatio sets the "completion_ratio" field if the given value is not nil.
func (_c *AccountUpstreamMonitorRateCreate) SetNillableCompletionRatio(v *float64) *AccountUpstreamMonitorRateCreate {
	if v != nil {
		_c.SetCompletionRatio(*v)
	}
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *AccountUpstreamMonitorRateCreate) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AccountUpstreamMonitorRateCreate) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// Mutation returns the AccountUpstreamMonitorRateMutation object of the builder.
func (_c *AccountUpstreamMonitorRateCreate) Mutation() *AccountUpstreamMonitorRateMutation {
	return _c.mutation
}

// Save creates the AccountUpstreamMonitorRate in the database.
func (_c *AccountUpstreamMonitorRateCreate) Save(ctx context.Context) (*AccountUpstreamMonitorRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUpstreamMonitorRateCreate) SaveX(ctx context.Context) *AccountUpstreamMonitorRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamMonitorRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamMonitorRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUpstreamMonitorRateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountupstreammonitorrate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountupstreammonitorrate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := accountupstreammonitorrate.DefaultProvider
		_c.mutation.SetProvider(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUpstreamMonitorRateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.account_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := accountupstreammonitorrate.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateKey(); !ok {
		return &ValidationError{Name: "rate_key", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.rate_key"`)}
	}
	if v, ok := _c.mutation.RateKey(); ok {
		if err := accountupstreammonitorrate.RateKeyValidator(v); err != nil {
			return &ValidationError{Name: "rate_key", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.rate_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := accountupstreammonitorrate.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.display_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := accountupstreammonitorrate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AccountUpstreamMonitorRate.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		return &ValidationError{Name: "ratio", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.ratio"`)}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "AccountUpstreamMonitorRate.last_seen_at"`)}
	}
	return nil
}

func (_c *AccountUpstreamMonitorRateCreate) sqlSave(ctx context.Context) (*AccountUpstreamMonitorRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUpstreamMonitorRateCreate) createSpec() (*AccountUpstreamMonitorRate, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUpstreamMonitorRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountupstreammonitorrate.Table, sqlgraph.NewFieldSpec(accountupstreammonitorrate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.RateKey(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRateKey, field.TypeString, value)
		_node.RateKey = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Ratio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldRatio, field.TypeFloat64, value)
		_node.Ratio = value
	}
	if value, ok := _c.mutation.CompletionRatio(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldCompletionRatio, field.TypeFloat64, value)
		_node.CompletionRatio = &value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(accountupstreammonitorrate.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamMonitorRate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamMonitorRateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorRateCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamMonitorRateUpsertOne {
	_c.conflict = opts
	return &AccountUpstreamMonitorRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorRateCreate) OnConflictColumns(columns ...string) *AccountUpstreamMonitorRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamMonitorRateUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpstreamMonitorRateUpsertOne is the builder for "upsert"-ing
	//  one AccountUpstreamMonitorRate node.
	AccountUpstreamMonitorRateUpsertOne struct {
		create *AccountUpstreamMonitorRateCreate
	}

	// AccountUpstreamMonitorRateUpsert is the "OnConflict" setter.
	AccountUpstreamMonitorRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorRateUpsert) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateUpdatedAt() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsert) SetAccountID(v int64) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateAccountID() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsert) AddAccountID(v int64) *AccountUpstreamMonitorRateUpsert {
	u.Add(accountupstreammonitorrate.FieldAccountID, v)
	return u
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorRateUpsert) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateProvider() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldProvider)
	return u
}

// SetRateKey sets the "rate_key" field.
func (u *AccountUpstreamMonitorRateUpsert) SetRateKey(v string) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldRateKey, v)
	return u
}

// UpdateRateKey sets the "rate_key" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateRateKey() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldRateKey)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpstreamMonitorRateUpsert) SetDisplayName(v string) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateDisplayName() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldDisplayName)
	return u
}

// SetDescription sets the "description" field.
func (u *AccountUpstreamMonitorRateUpsert) SetDescription(v string) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateDescription() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpstreamMonitorRateUpsert) ClearDescription() *AccountUpstreamMonitorRateUpsert {
	u.SetNull(accountupstreammonitorrate.FieldDescription)
	return u
}

// SetRatio sets the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsert) SetRatio(v float64) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldRatio, v)
	return u
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateRatio() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldRatio)
	return u
}

// AddRatio adds v to the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsert) AddRatio(v float64) *AccountUpstreamMonitorRateUpsert {
	u.Add(accountupstreammonitorrate.FieldRatio, v)
	return u
}

// SetCompletionRatio sets the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsert) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldCompletionRatio, v)
	return u
}

// UpdateCompletionRatio sets the "completion_ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateCompletionRatio() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldCompletionRatio)
	return u
}

// AddCompletionRatio adds v to the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsert) AddCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsert {
	u.Add(accountupstreammonitorrate.FieldCompletionRatio, v)
	return u
}

// ClearCompletionRatio clears the value of the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsert) ClearCompletionRatio() *AccountUpstreamMonitorRateUpsert {
	u.SetNull(accountupstreammonitorrate.FieldCompletionRatio)
	return u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsert) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldFirstSeenAt, v)
	return u
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateFirstSeenAt() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldFirstSeenAt)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsert) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsert {
	u.Set(accountupstreammonitorrate.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsert) UpdateLastSeenAt() *AccountUpstreamMonitorRateUpsert {
	u.SetExcluded(accountupstreammonitorrate.FieldLastSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateNewValues() *AccountUpstreamMonitorRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountupstreammonitorrate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpstreamMonitorRateUpsertOne) Ignore() *AccountUpstreamMonitorRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamMonitorRateUpsertOne) DoNothing() *AccountUpstreamMonitorRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamMonitorRateCreate.OnConflict
// documentation for more info.
func (u *AccountUpstreamMonitorRateUpsertOne) Update(set func(*AccountUpstreamMonitorRateUpsert)) *AccountUpstreamMonitorRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamMonitorRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateUpdatedAt() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetAccountID(v int64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsertOne) AddAccountID(v int64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateAccountID() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateProvider() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateProvider()
	})
}

// SetRateKey sets the "rate_key" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetRateKey(v string) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetRateKey(v)
	})
}

// UpdateRateKey sets the "rate_key" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateRateKey() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateRateKey()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetDisplayName(v string) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateDisplayName() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetDescription(v string) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateDescription() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpstreamMonitorRateUpsertOne) ClearDescription() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.ClearDescription()
	})
}

// SetRatio sets the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetRatio(v float64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetRatio(v)
	})
}

// AddRatio adds v to the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsertOne) AddRatio(v float64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateRatio() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateRatio()
	})
}

// SetCompletionRatio sets the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetCompletionRatio(v)
	})
}

// AddCompletionRatio adds v to the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertOne) AddCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddCompletionRatio(v)
	})
}

// UpdateCompletionRatio sets the "completion_ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateCompletionRatio() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateCompletionRatio()
	})
}

// ClearCompletionRatio clears the value of the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertOne) ClearCompletionRatio() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.ClearCompletionRatio()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateFirstSeenAt() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsertOne) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertOne) UpdateLastSeenAt() *AccountUpstreamMonitorRateUpsertOne {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *AccountUpstreamMonitorRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamMonitorRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamMonitorRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpstreamMonitorRateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpstreamMonitorRateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUpstreamMonitorRateCreateBulk is the builder for creating many AccountUpstreamMonitorRate entities in bulk.
type AccountUpstreamMonitorRateCreateBulk struct {
	config
	err      error
	builders []*AccountUpstreamMonitorRateCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUpstreamMonitorRate entities in the database.
func (_c *AccountUpstreamMonitorRateCreateBulk) Save(ctx context.Context) ([]*AccountUpstreamMonitorRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUpstreamMonitorRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUpstreamMonitorRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUpstreamMonitorRateCreateBulk) SaveX(ctx context.Context) []*AccountUpstreamMonitorRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUpstreamMonitorRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUpstreamMonitorRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUpstreamMonitorRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpstreamMonitorRateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpstreamMonitorRateUpsertBulk {
	_c.conflict = opts
	return &AccountUpstreamMonitorRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUpstreamMonitorRateCreateBulk) OnConflictColumns(columns ...string) *AccountUpstreamMonitorRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpstreamMonitorRateUpsertBulk{
		create: _c,
	}
}

// AccountUpstreamMonitorRateUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUpstreamMonitorRate nodes.
type AccountUpstreamMonitorRateUpsertBulk struct {
	create *AccountUpstreamMonitorRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateNewValues() *AccountUpstreamMonitorRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountupstreammonitorrate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUpstreamMonitorRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpstreamMonitorRateUpsertBulk) Ignore() *AccountUpstreamMonitorRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpstreamMonitorRateUpsertBulk) DoNothing() *AccountUpstreamMonitorRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUpstreamMonitorRateCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpstreamMonitorRateUpsertBulk) Update(set func(*AccountUpstreamMonitorRateUpsert)) *AccountUpstreamMonitorRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpstreamMonitorRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateUpdatedAt() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetAccountID(v int64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) AddAccountID(v int64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateAccountID() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateAccountID()
	})
}

// SetProvider sets the "provider" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetProvider(v accountupstreammonitorrate.Provider) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateProvider() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateProvider()
	})
}

// SetRateKey sets the "rate_key" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetRateKey(v string) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetRateKey(v)
	})
}

// UpdateRateKey sets the "rate_key" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateRateKey() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateRateKey()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetDisplayName(v string) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateDisplayName() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetDescription(v string) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateDescription() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) ClearDescription() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.ClearDescription()
	})
}

// SetRatio sets the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetRatio(v float64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetRatio(v)
	})
}

// AddRatio adds v to the "ratio" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) AddRatio(v float64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateRatio() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateRatio()
	})
}

// SetCompletionRatio sets the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetCompletionRatio(v)
	})
}

// AddCompletionRatio adds v to the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) AddCompletionRatio(v float64) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.AddCompletionRatio(v)
	})
}

// UpdateCompletionRatio sets the "completion_ratio" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateCompletionRatio() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateCompletionRatio()
	})
}

// ClearCompletionRatio clears the value of the "completion_ratio" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) ClearCompletionRatio() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.ClearCompletionRatio()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetFirstSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateFirstSeenAt() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AccountUpstreamMonitorRateUpsertBulk) SetLastSeenAt(v time.Time) *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AccountUpstreamMonitorRateUpsertBulk) UpdateLastSeenAt() *AccountUpstreamMonitorRateUpsertBulk {
	return u.Update(func(s *AccountUpstreamMonitorRateUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *AccountUpstreamMonitorRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUpstreamMonitorRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUpstreamMonitorRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpstreamMonitorRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
