// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountbalancebinding"
	"github.com/Wei-Shaw/sub2api/ent/balancekeysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceSiteQuery is the builder for querying BalanceSite entities.
type BalanceSiteQuery struct {
	config
	ctx           *QueryContext
	order         []balancesite.OrderOption
	inters        []Interceptor
	predicates    []predicate.BalanceSite
	withSnapshots *BalanceKeySnapshotQuery
	withBindings  *AccountBalanceBindingQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BalanceSiteQuery builder.
func (_q *BalanceSiteQuery) Where(ps ...predicate.BalanceSite) *BalanceSiteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BalanceSiteQuery) Limit(limit int) *BalanceSiteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BalanceSiteQuery) Offset(offset int) *BalanceSiteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BalanceSiteQuery) Unique(unique bool) *BalanceSiteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BalanceSiteQuery) Order(o ...balancesite.OrderOption) *BalanceSiteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySnapshots chains the current query on the "snapshots" edge.
func (_q *BalanceSiteQuery) QuerySnapshots() *BalanceKeySnapshotQuery {
	query := (&BalanceKeySnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(balancesite.Table, balancesite.FieldID, selector),
			sqlgraph.To(balancekeysnapshot.Table, balancekeysnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, balancesite.SnapshotsTable, balancesite.SnapshotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBindings chains the current query on the "bindings" edge.
func (_q *BalanceSiteQuery) QueryBindings() *AccountBalanceBindingQuery {
	query := (&AccountBalanceBindingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(balancesite.Table, balancesite.FieldID, selector),
			sqlgraph.To(accountbalancebinding.Table, accountbalancebinding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, balancesite.BindingsTable, balancesite.BindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BalanceSite entity from the query.
// Returns a *NotFoundError when no BalanceSite was found.
func (_q *BalanceSiteQuery) First(ctx context.Context) (*BalanceSite, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{balancesite.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BalanceSiteQuery) FirstX(ctx context.Context) *BalanceSite {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BalanceSite ID from the query.
// Returns a *NotFoundError when no BalanceSite ID was found.
func (_q *BalanceSiteQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{balancesite.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BalanceSiteQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BalanceSite entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BalanceSite entity is found.
// Returns a *NotFoundError when no BalanceSite entities are found.
func (_q *BalanceSiteQuery) Only(ctx context.Context) (*BalanceSite, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{balancesite.Label}
	default:
		return nil, &NotSingularError{balancesite.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BalanceSiteQuery) OnlyX(ctx context.Context) *BalanceSite {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BalanceSite ID in the query.
// Returns a *NotSingularError when more than one BalanceSite ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BalanceSiteQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{balancesite.Label}
	default:
		err = &NotSingularError{balancesite.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BalanceSiteQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BalanceSites.
func (_q *BalanceSiteQuery) All(ctx context.Context) ([]*BalanceSite, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BalanceSite, *BalanceSiteQuery]()
	return withInterceptors[[]*BalanceSite](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BalanceSiteQuery) AllX(ctx context.Context) []*BalanceSite {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BalanceSite IDs.
func (_q *BalanceSiteQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(balancesite.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BalanceSiteQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BalanceSiteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BalanceSiteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BalanceSiteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BalanceSiteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BalanceSiteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BalanceSiteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BalanceSiteQuery) Clone() *BalanceSiteQuery {
	if _q == nil {
		return nil
	}
	return &BalanceSiteQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]balancesite.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.BalanceSite{}, _q.predicates...),
		withSnapshots: _q.withSnapshots.Clone(),
		withBindings:  _q.withBindings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSnapshots tells the query-builder to eager-load the nodes that are connected to
// the "snapshots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BalanceSiteQuery) WithSnapshots(opts ...func(*BalanceKeySnapshotQuery)) *BalanceSiteQuery {
	query := (&BalanceKeySnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapshots = query
	return _q
}

// WithBindings tells the query-builder to eager-load the nodes that are connected to
// the "bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BalanceSiteQuery) WithBindings(opts ...func(*AccountBalanceBindingQuery)) *BalanceSiteQuery {
	query := (&AccountBalanceBindingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBindings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BalanceSite.Query().
//		GroupBy(balancesite.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BalanceSiteQuery) GroupBy(field string, fields ...string) *BalanceSiteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BalanceSiteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = balancesite.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.BalanceSite.Query().
//		Select(balancesite.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *BalanceSiteQuery) Select(fields ...string) *BalanceSiteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BalanceSiteSelect{BalanceSiteQuery: _q}
	sbuild.label = balancesite.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BalanceSiteSelect configured with the given aggregations.
func (_q *BalanceSiteQuery) Aggregate(fns ...AggregateFunc) *BalanceSiteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BalanceSiteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !balancesite.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BalanceSiteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BalanceSite, error) {
	var (
		nodes       = []*BalanceSite{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSnapshots != nil,
			_q.withBindings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BalanceSite).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BalanceSite{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSnapshots; query != nil {
		if err := _q.loadSnapshots(ctx, query, nodes,
			func(n *BalanceSite) { n.Edges.Snapshots = []*BalanceKeySnapshot{} },
			func(n *BalanceSite, e *BalanceKeySnapshot) { n.Edges.Snapshots = append(n.Edges.Snapshots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBindings; query != nil {
		if err := _q.loadBindings(ctx, query, nodes,
			func(n *BalanceSite) { n.Edges.Bindings = []*AccountBalanceBinding{} },
			func(n *BalanceSite, e *AccountBalanceBinding) { n.Edges.Bindings = append(n.Edges.Bindings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BalanceSiteQuery) loadSnapshots(ctx context.Context, query *BalanceKeySnapshotQuery, nodes []*BalanceSite, init func(*BalanceSite), assign func(*BalanceSite, *BalanceKeySnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*BalanceSite)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(balancekeysnapshot.FieldSiteID)
	}
	query.Where(predicate.BalanceKeySnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(balancesite.SnapshotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SiteID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "site_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BalanceSiteQuery) loadBindings(ctx context.Context, query *AccountBalanceBindingQuery, nodes []*BalanceSite, init func(*BalanceSite), assign func(*BalanceSite, *AccountBalanceBinding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*BalanceSite)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(accountbalancebinding.FieldSiteID)
	}
	query.Where(predicate.AccountBalanceBinding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(balancesite.BindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SiteID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "site_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BalanceSiteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BalanceSiteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(balancesite.Table, balancesite.Columns, sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancesite.FieldID)
		for i := range fields {
			if fields[i] != balancesite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BalanceSiteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(balancesite.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = balancesite.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *BalanceSiteQuery) ForUpdate(opts ...sql.LockOption) *BalanceSiteQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *BalanceSiteQuery) ForShare(opts ...sql.LockOption) *BalanceSiteQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// BalanceSiteGroupBy is the group-by builder for BalanceSite entities.
type BalanceSiteGroupBy struct {
	selector
	build *BalanceSiteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BalanceSiteGroupBy) Aggregate(fns ...AggregateFunc) *BalanceSiteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BalanceSiteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BalanceSiteQuery, *BalanceSiteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BalanceSiteGroupBy) sqlScan(ctx context.Context, root *BalanceSiteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BalanceSiteSelect is the builder for selecting fields of BalanceSite entities.
type BalanceSiteSelect struct {
	*BalanceSiteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BalanceSiteSelect) Aggregate(fns ...AggregateFunc) *BalanceSiteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BalanceSiteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BalanceSiteQuery, *BalanceSiteSelect](ctx, _s.BalanceSiteQuery, _s, _s.inters, v)
}

func (_s *BalanceSiteSelect) sqlScan(ctx context.Context, root *BalanceSiteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
