// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
)

// BalanceSite is the model entity for the BalanceSite schema.
type BalanceSite struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform balancesite.Platform `json:"platform,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// AuthMode holds the value of the "auth_mode" field.
	AuthMode balancesite.AuthMode `json:"auth_mode,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordEncrypted holds the value of the "password_encrypted" field.
	PasswordEncrypted string `json:"-"`
	// AccessTokenEncrypted holds the value of the "access_token_encrypted" field.
	AccessTokenEncrypted string `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// RefreshIntervalMinutes holds the value of the "refresh_interval_minutes" field.
	RefreshIntervalMinutes int `json:"refresh_interval_minutes,omitempty"`
	// LastRefreshAt holds the value of the "last_refresh_at" field.
	LastRefreshAt *time.Time `json:"last_refresh_at,omitempty"`
	// LastRefreshStatus holds the value of the "last_refresh_status" field.
	LastRefreshStatus string `json:"last_refresh_status,omitempty"`
	// LastRefreshError holds the value of the "last_refresh_error" field.
	LastRefreshError *string `json:"last_refresh_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BalanceSiteQuery when eager-loading is set.
	Edges        BalanceSiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BalanceSiteEdges holds the relations/edges for other nodes in the graph.
type BalanceSiteEdges struct {
	// Snapshots holds the value of the snapshots edge.
	Snapshots []*BalanceKeySnapshot `json:"snapshots,omitempty"`
	// Bindings holds the value of the bindings edge.
	Bindings []*AccountBalanceBinding `json:"bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SnapshotsOrErr returns the Snapshots value or an error if the edge
// was not loaded in eager-loading.
func (e BalanceSiteEdges) SnapshotsOrErr() ([]*BalanceKeySnapshot, error) {
	if e.loadedTypes[0] {
		return e.Snapshots, nil
	}
	return nil, &NotLoadedError{edge: "snapshots"}
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e BalanceSiteEdges) BindingsOrErr() ([]*AccountBalanceBinding, error) {
	if e.loadedTypes[1] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceSite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancesite.FieldEnabled:
			values[i] = new(sql.NullBool)
		case balancesite.FieldID, balancesite.FieldRefreshIntervalMinutes:
			values[i] = new(sql.NullInt64)
		case balancesite.FieldPlatform, balancesite.FieldName, balancesite.FieldBaseURL, balancesite.FieldAuthMode, balancesite.FieldUsername, balancesite.FieldEmail, balancesite.FieldPasswordEncrypted, balancesite.FieldAccessTokenEncrypted, balancesite.FieldLastRefreshStatus, balancesite.FieldLastRefreshError:
			values[i] = new(sql.NullString)
		case balancesite.FieldCreatedAt, balancesite.FieldUpdatedAt, balancesite.FieldLastRefreshAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceSite fields.
func (_m *BalanceSite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancesite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balancesite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case balancesite.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case balancesite.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = balancesite.Platform(value.String)
			}
		case balancesite.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case balancesite.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case balancesite.FieldAuthMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_mode", values[i])
			} else if value.Valid {
				_m.AuthMode = balancesite.AuthMode(value.String)
			}
		case balancesite.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case balancesite.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case balancesite.FieldPasswordEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_encrypted", values[i])
			} else if value.Valid {
				_m.PasswordEncrypted = value.String
			}
		case balancesite.FieldAccessTokenEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_encrypted", values[i])
			} else if value.Valid {
				_m.AccessTokenEncrypted = value.String
			}
		case balancesite.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case balancesite.FieldRefreshIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_minutes", values[i])
			} else if value.Valid {
				_m.RefreshIntervalMinutes = int(value.Int64)
			}
		case balancesite.FieldLastRefreshAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_at", values[i])
			} else if value.Valid {
				_m.LastRefreshAt = new(time.Time)
				*_m.LastRefreshAt = value.Time
			}
		case balancesite.FieldLastRefreshStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_status", values[i])
			} else if value.Valid {
				_m.LastRefreshStatus = value.String
			}
		case balancesite.FieldLastRefreshError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_error", values[i])
			} else if value.Valid {
				_m.LastRefreshError = new(string)
				*_m.LastRefreshError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceSite.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceSite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshots queries the "snapshots" edge of the BalanceSite entity.
func (_m *BalanceSite) QuerySnapshots() *BalanceKeySnapshotQuery {
	return NewBalanceSiteClient(_m.config).QuerySnapshots(_m)
}

// QueryBindings queries the "bindings" edge of the BalanceSite entity.
func (_m *BalanceSite) QueryBindings() *AccountBalanceBindingQuery {
	return NewBalanceSiteClient(_m.config).QueryBindings(_m)
}

// Update returns a builder for updating this BalanceSite.
// Note that you need to call BalanceSite.Unwrap() before calling this method if this BalanceSite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceSite) Update() *BalanceSiteUpdateOne {
	return NewBalanceSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceSite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceSite) Unwrap() *BalanceSite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceSite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceSite) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceSite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("auth_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMode))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("access_token_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("refresh_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshIntervalMinutes))
	builder.WriteString(", ")
	if v := _m.LastRefreshAt; v != nil {
		builder.WriteString("last_refresh_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_refresh_status=")
	builder.WriteString(_m.LastRefreshStatus)
	builder.WriteString(", ")
	if v := _m.LastRefreshError; v != nil {
		builder.WriteString("last_refresh_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BalanceSites is a parsable slice of BalanceSite.
type BalanceSites []*BalanceSite
