// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/balancekeysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceKeySnapshotUpdate is the builder for updating BalanceKeySnapshot entities.
type BalanceKeySnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceKeySnapshotMutation
}

// Where appends a list predicates to the BalanceKeySnapshotUpdate builder.
func (_u *BalanceKeySnapshotUpdate) Where(ps ...predicate.BalanceKeySnapshot) *BalanceKeySnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceKeySnapshotUpdate) SetUpdatedAt(v time.Time) *BalanceKeySnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *BalanceKeySnapshotUpdate) SetSiteID(v int64) *BalanceKeySnapshotUpdate {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableSiteID(v *int64) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetExternalKeyID sets the "external_key_id" field.
func (_u *BalanceKeySnapshotUpdate) SetExternalKeyID(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetExternalKeyID(v)
	return _u
}

// SetNillableExternalKeyID sets the "external_key_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableExternalKeyID(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetExternalKeyID(*v)
	}
	return _u
}

// SetMaskedKey sets the "masked_key" field.
func (_u *BalanceKeySnapshotUpdate) SetMaskedKey(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetMaskedKey(v)
	return _u
}

// SetNillableMaskedKey sets the "masked_key" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableMaskedKey(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetMaskedKey(*v)
	}
	return _u
}

// SetKeyLast4 sets the "key_last4" field.
func (_u *BalanceKeySnapshotUpdate) SetKeyLast4(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetKeyLast4(v)
	return _u
}

// SetNillableKeyLast4 sets the "key_last4" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableKeyLast4(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetKeyLast4(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BalanceKeySnapshotUpdate) SetAccountID(v int64) *BalanceKeySnapshotUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableAccountID(v *int64) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *BalanceKeySnapshotUpdate) ClearAccountID() *BalanceKeySnapshotUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetMatchStatus sets the "match_status" field.
func (_u *BalanceKeySnapshotUpdate) SetMatchStatus(v balancekeysnapshot.MatchStatus) *BalanceKeySnapshotUpdate {
	_u.mutation.SetMatchStatus(v)
	return _u
}

// SetNillableMatchStatus sets the "match_status" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableMatchStatus(v *balancekeysnapshot.MatchStatus) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetMatchStatus(*v)
	}
	return _u
}

// SetKeyName sets the "key_name" field.
func (_u *BalanceKeySnapshotUpdate) SetKeyName(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetKeyName(v)
	return _u
}

// SetNillableKeyName sets the "key_name" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableKeyName(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetKeyName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceKeySnapshotUpdate) SetStatus(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableStatus(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BalanceKeySnapshotUpdate) SetGroupID(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableGroupID(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *BalanceKeySnapshotUpdate) SetGroupName(v string) *BalanceKeySnapshotUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableGroupName(v *string) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *BalanceKeySnapshotUpdate) SetBalance(v map[string]interface{}) *BalanceKeySnapshotUpdate {
	_u.mutation.SetBalance(v)
	return _u
}

// SetSubscriptionBalance sets the "subscription_balance" field.
func (_u *BalanceKeySnapshotUpdate) SetSubscriptionBalance(v map[string]interface{}) *BalanceKeySnapshotUpdate {
	_u.mutation.SetSubscriptionBalance(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdate) SetRateMultiplier(v float64) *BalanceKeySnapshotUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableRateMultiplier(v *float64) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdate) AddRateMultiplier(v float64) *BalanceKeySnapshotUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// ClearRateMultiplier clears the value of the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdate) ClearRateMultiplier() *BalanceKeySnapshotUpdate {
	_u.mutation.ClearRateMultiplier()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *BalanceKeySnapshotUpdate) SetFetchedAt(v time.Time) *BalanceKeySnapshotUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdate) SetNillableFetchedAt(v *time.Time) *BalanceKeySnapshotUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the BalanceSite entity.
func (_u *BalanceKeySnapshotUpdate) SetSite(v *BalanceSite) *BalanceKeySnapshotUpdate {
	return _u.SetSiteID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BalanceKeySnapshotUpdate) SetAccount(v *Account) *BalanceKeySnapshotUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the BalanceKeySnapshotMutation object of the builder.
func (_u *BalanceKeySnapshotUpdate) Mutation() *BalanceKeySnapshotMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the BalanceSite entity.
func (_u *BalanceKeySnapshotUpdate) ClearSite() *BalanceKeySnapshotUpdate {
	_u.mutation.ClearSite()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BalanceKeySnapshotUpdate) ClearAccount() *BalanceKeySnapshotUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceKeySnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceKeySnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceKeySnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceKeySnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceKeySnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancekeysnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceKeySnapshotUpdate) check() error {
	if v, ok := _u.mutation.ExternalKeyID(); ok {
		if err := balancekeysnapshot.ExternalKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "external_key_id", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.external_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaskedKey(); ok {
		if err := balancekeysnapshot.MaskedKeyValidator(v); err != nil {
			return &ValidationError{Name: "masked_key", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.masked_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyLast4(); ok {
		if err := balancekeysnapshot.KeyLast4Validator(v); err != nil {
			return &ValidationError{Name: "key_last4", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.key_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchStatus(); ok {
		if err := balancekeysnapshot.MatchStatusValidator(v); err != nil {
			return &ValidationError{Name: "match_status", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.match_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyName(); ok {
		if err := balancekeysnapshot.KeyNameValidator(v); err != nil {
			return &ValidationError{Name: "key_name", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.key_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancekeysnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := balancekeysnapshot.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := balancekeysnapshot.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.group_name": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceKeySnapshot.site"`)
	}
	return nil
}

func (_u *BalanceKeySnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancekeysnapshot.Table, balancekeysnapshot.Columns, sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancekeysnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalKeyID(); ok {
		_spec.SetField(balancekeysnapshot.FieldExternalKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaskedKey(); ok {
		_spec.SetField(balancekeysnapshot.FieldMaskedKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyLast4(); ok {
		_spec.SetField(balancekeysnapshot.FieldKeyLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchStatus(); ok {
		_spec.SetField(balancekeysnapshot.FieldMatchStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KeyName(); ok {
		_spec.SetField(balancekeysnapshot.FieldKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancekeysnapshot.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(balancekeysnapshot.FieldGroupID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(balancekeysnapshot.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(balancekeysnapshot.FieldBalance, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SubscriptionBalance(); ok {
		_spec.SetField(balancekeysnapshot.FieldSubscriptionBalance, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.RateMultiplierCleared() {
		_spec.ClearField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(balancekeysnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancekeysnapshot.SiteTable,
			Columns: []string{balancekeysnapshot.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancekeysnapshot.SiteTable,
			Columns: []string{balancekeysnapshot.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   balancekeysnapshot.AccountTable,
			Columns: []string{balancekeysnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   balancekeysnapshot.AccountTable,
			Columns: []string{balancekeysnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancekeysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceKeySnapshotUpdateOne is the builder for updating a single BalanceKeySnapshot entity.
type BalanceKeySnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceKeySnapshotMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceKeySnapshotUpdateOne) SetUpdatedAt(v time.Time) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *BalanceKeySnapshotUpdateOne) SetSiteID(v int64) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableSiteID(v *int64) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetExternalKeyID sets the "external_key_id" field.
func (_u *BalanceKeySnapshotUpdateOne) SetExternalKeyID(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetExternalKeyID(v)
	return _u
}

// SetNillableExternalKeyID sets the "external_key_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableExternalKeyID(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetExternalKeyID(*v)
	}
	return _u
}

// SetMaskedKey sets the "masked_key" field.
func (_u *BalanceKeySnapshotUpdateOne) SetMaskedKey(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetMaskedKey(v)
	return _u
}

// SetNillableMaskedKey sets the "masked_key" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableMaskedKey(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetMaskedKey(*v)
	}
	return _u
}

// SetKeyLast4 sets the "key_last4" field.
func (_u *BalanceKeySnapshotUpdateOne) SetKeyLast4(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetKeyLast4(v)
	return _u
}

// SetNillableKeyLast4 sets the "key_last4" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableKeyLast4(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetKeyLast4(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BalanceKeySnapshotUpdateOne) SetAccountID(v int64) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableAccountID(v *int64) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *BalanceKeySnapshotUpdateOne) ClearAccountID() *BalanceKeySnapshotUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetMatchStatus sets the "match_status" field.
func (_u *BalanceKeySnapshotUpdateOne) SetMatchStatus(v balancekeysnapshot.MatchStatus) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetMatchStatus(v)
	return _u
}

// SetNillableMatchStatus sets the "match_status" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableMatchStatus(v *balancekeysnapshot.MatchStatus) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetMatchStatus(*v)
	}
	return _u
}

// SetKeyName sets the "key_name" field.
func (_u *BalanceKeySnapshotUpdateOne) SetKeyName(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetKeyName(v)
	return _u
}

// SetNillableKeyName sets the "key_name" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableKeyName(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetKeyName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceKeySnapshotUpdateOne) SetStatus(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableStatus(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BalanceKeySnapshotUpdateOne) SetGroupID(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableGroupID(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *BalanceKeySnapshotUpdateOne) SetGroupName(v string) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableGroupName(v *string) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *BalanceKeySnapshotUpdateOne) SetBalance(v map[string]interface{}) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetBalance(v)
	return _u
}

// SetSubscriptionBalance sets the "subscription_balance" field.
func (_u *BalanceKeySnapshotUpdateOne) SetSubscriptionBalance(v map[string]interface{}) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetSubscriptionBalance(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdateOne) SetRateMultiplier(v float64) *BalanceKeySnapshotUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableRateMultiplier(v *float64) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdateOne) AddRateMultiplier(v float64) *BalanceKeySnapshotUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// ClearRateMultiplier clears the value of the "rate_multiplier" field.
func (_u *BalanceKeySnapshotUpdateOne) ClearRateMultiplier() *BalanceKeySnapshotUpdateOne {
	_u.mutation.ClearRateMultiplier()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *BalanceKeySnapshotUpdateOne) SetFetchedAt(v time.Time) *BalanceKeySnapshotUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *BalanceKeySnapshotUpdateOne) SetNillableFetchedAt(v *time.Time) *BalanceKeySnapshotUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the BalanceSite entity.
func (_u *BalanceKeySnapshotUpdateOne) SetSite(v *BalanceSite) *BalanceKeySnapshotUpdateOne {
	return _u.SetSiteID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BalanceKeySnapshotUpdateOne) SetAccount(v *Account) *BalanceKeySnapshotUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the BalanceKeySnapshotMutation object of the builder.
func (_u *BalanceKeySnapshotUpdateOne) Mutation() *BalanceKeySnapshotMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the BalanceSite entity.
func (_u *BalanceKeySnapshotUpdateOne) ClearSite() *BalanceKeySnapshotUpdateOne {
	_u.mutation.ClearSite()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BalanceKeySnapshotUpdateOne) ClearAccount() *BalanceKeySnapshotUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the BalanceKeySnapshotUpdate builder.
func (_u *BalanceKeySnapshotUpdateOne) Where(ps ...predicate.BalanceKeySnapshot) *BalanceKeySnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceKeySnapshotUpdateOne) Select(field string, fields ...string) *BalanceKeySnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceKeySnapshot entity.
func (_u *BalanceKeySnapshotUpdateOne) Save(ctx context.Context) (*BalanceKeySnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceKeySnapshotUpdateOne) SaveX(ctx context.Context) *BalanceKeySnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceKeySnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceKeySnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceKeySnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancekeysnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceKeySnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalKeyID(); ok {
		if err := balancekeysnapshot.ExternalKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "external_key_id", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.external_key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaskedKey(); ok {
		if err := balancekeysnapshot.MaskedKeyValidator(v); err != nil {
			return &ValidationError{Name: "masked_key", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.masked_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyLast4(); ok {
		if err := balancekeysnapshot.KeyLast4Validator(v); err != nil {
			return &ValidationError{Name: "key_last4", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.key_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchStatus(); ok {
		if err := balancekeysnapshot.MatchStatusValidator(v); err != nil {
			return &ValidationError{Name: "match_status", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.match_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyName(); ok {
		if err := balancekeysnapshot.KeyNameValidator(v); err != nil {
			return &ValidationError{Name: "key_name", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.key_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancekeysnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := balancekeysnapshot.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := balancekeysnapshot.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "BalanceKeySnapshot.group_name": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceKeySnapshot.site"`)
	}
	return nil
}

func (_u *BalanceKeySnapshotUpdateOne) sqlSave(ctx context.Context) (_node *BalanceKeySnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancekeysnapshot.Table, balancekeysnapshot.Columns, sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceKeySnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancekeysnapshot.FieldID)
		for _, f := range fields {
			if !balancekeysnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancekeysnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancekeysnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalKeyID(); ok {
		_spec.SetField(balancekeysnapshot.FieldExternalKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaskedKey(); ok {
		_spec.SetField(balancekeysnapshot.FieldMaskedKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyLast4(); ok {
		_spec.SetField(balancekeysnapshot.FieldKeyLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchStatus(); ok {
		_spec.SetField(balancekeysnapshot.FieldMatchStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KeyName(); ok {
		_spec.SetField(balancekeysnapshot.FieldKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancekeysnapshot.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(balancekeysnapshot.FieldGroupID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(balancekeysnapshot.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(balancekeysnapshot.FieldBalance, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SubscriptionBalance(); ok {
		_spec.SetField(balancekeysnapshot.FieldSubscriptionBalance, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.RateMultiplierCleared() {
		_spec.ClearField(balancekeysnapshot.FieldRateMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(balancekeysnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancekeysnapshot.SiteTable,
			Columns: []string{balancekeysnapshot.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancekeysnapshot.SiteTable,
			Columns: []string{balancekeysnapshot.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   balancekeysnapshot.AccountTable,
			Columns: []string{balancekeysnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   balancekeysnapshot.AccountTable,
			Columns: []string{balancekeysnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceKeySnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancekeysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
