// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountbalancebinding"
	"github.com/Wei-Shaw/sub2api/ent/balancekeysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceSiteUpdate is the builder for updating BalanceSite entities.
type BalanceSiteUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceSiteMutation
}

// Where appends a list predicates to the BalanceSiteUpdate builder.
func (_u *BalanceSiteUpdate) Where(ps ...predicate.BalanceSite) *BalanceSiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceSiteUpdate) SetUpdatedAt(v time.Time) *BalanceSiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *BalanceSiteUpdate) SetPlatform(v balancesite.Platform) *BalanceSiteUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillablePlatform(v *balancesite.Platform) *BalanceSiteUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BalanceSiteUpdate) SetName(v string) *BalanceSiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableName(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *BalanceSiteUpdate) SetBaseURL(v string) *BalanceSiteUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableBaseURL(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *BalanceSiteUpdate) SetAuthMode(v balancesite.AuthMode) *BalanceSiteUpdate {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableAuthMode(v *balancesite.AuthMode) *BalanceSiteUpdate {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *BalanceSiteUpdate) SetUsername(v string) *BalanceSiteUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableUsername(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *BalanceSiteUpdate) SetEmail(v string) *BalanceSiteUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableEmail(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *BalanceSiteUpdate) SetPasswordEncrypted(v string) *BalanceSiteUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillablePasswordEncrypted(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_u *BalanceSiteUpdate) SetAccessTokenEncrypted(v string) *BalanceSiteUpdate {
	_u.mutation.SetAccessTokenEncrypted(v)
	return _u
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableAccessTokenEncrypted(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetAccessTokenEncrypted(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BalanceSiteUpdate) SetEnabled(v bool) *BalanceSiteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableEnabled(v *bool) *BalanceSiteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *BalanceSiteUpdate) SetRefreshIntervalMinutes(v int) *BalanceSiteUpdate {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableRefreshIntervalMinutes(v *int) *BalanceSiteUpdate {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *BalanceSiteUpdate) AddRefreshIntervalMinutes(v int) *BalanceSiteUpdate {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *BalanceSiteUpdate) SetLastRefreshAt(v time.Time) *BalanceSiteUpdate {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableLastRefreshAt(v *time.Time) *BalanceSiteUpdate {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *BalanceSiteUpdate) ClearLastRefreshAt() *BalanceSiteUpdate {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (_u *BalanceSiteUpdate) SetLastRefreshStatus(v string) *BalanceSiteUpdate {
	_u.mutation.SetLastRefreshStatus(v)
	return _u
}

// SetNillableLastRefreshStatus sets the "last_refresh_status" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableLastRefreshStatus(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetLastRefreshStatus(*v)
	}
	return _u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_u *BalanceSiteUpdate) SetLastRefreshError(v string) *BalanceSiteUpdate {
	_u.mutation.SetLastRefreshError(v)
	return _u
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_u *BalanceSiteUpdate) SetNillableLastRefreshError(v *string) *BalanceSiteUpdate {
	if v != nil {
		_u.SetLastRefreshError(*v)
	}
	return _u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (_u *BalanceSiteUpdate) ClearLastRefreshError() *BalanceSiteUpdate {
	_u.mutation.ClearLastRefreshError()
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the BalanceKeySnapshot entity by IDs.
func (_u *BalanceSiteUpdate) AddSnapshotIDs(ids ...int64) *BalanceSiteUpdate {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the BalanceKeySnapshot entity.
func (_u *BalanceSiteUpdate) AddSnapshots(v ...*BalanceKeySnapshot) *BalanceSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddBindingIDs adds the "bindings" edge to the AccountBalanceBinding entity by IDs.
func (_u *BalanceSiteUpdate) AddBindingIDs(ids ...int64) *BalanceSiteUpdate {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the AccountBalanceBinding entity.
func (_u *BalanceSiteUpdate) AddBindings(v ...*AccountBalanceBinding) *BalanceSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the BalanceSiteMutation object of the builder.
func (_u *BalanceSiteUpdate) Mutation() *BalanceSiteMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the BalanceKeySnapshot entity.
func (_u *BalanceSiteUpdate) ClearSnapshots() *BalanceSiteUpdate {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to BalanceKeySnapshot entities by IDs.
func (_u *BalanceSiteUpdate) RemoveSnapshotIDs(ids ...int64) *BalanceSiteUpdate {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to BalanceKeySnapshot entities.
func (_u *BalanceSiteUpdate) RemoveSnapshots(v ...*BalanceKeySnapshot) *BalanceSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearBindings clears all "bindings" edges to the AccountBalanceBinding entity.
func (_u *BalanceSiteUpdate) ClearBindings() *BalanceSiteUpdate {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to AccountBalanceBinding entities by IDs.
func (_u *BalanceSiteUpdate) RemoveBindingIDs(ids ...int64) *BalanceSiteUpdate {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to AccountBalanceBinding entities.
func (_u *BalanceSiteUpdate) RemoveBindings(v ...*AccountBalanceBinding) *BalanceSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceSiteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceSiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceSiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceSiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceSiteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancesite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceSiteUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := balancesite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := balancesite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := balancesite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := balancesite.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := balancesite.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := balancesite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		if err := balancesite.RefreshIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "refresh_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.refresh_interval_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastRefreshStatus(); ok {
		if err := balancesite.LastRefreshStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_refresh_status", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.last_refresh_status": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceSiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancesite.Table, balancesite.Columns, sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancesite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(balancesite.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balancesite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(balancesite.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(balancesite.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(balancesite.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(balancesite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(balancesite.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(balancesite.FieldAccessTokenEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(balancesite.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(balancesite.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(balancesite.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(balancesite.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(balancesite.FieldLastRefreshAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshStatus(); ok {
		_spec.SetField(balancesite.FieldLastRefreshStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRefreshError(); ok {
		_spec.SetField(balancesite.FieldLastRefreshError, field.TypeString, value)
	}
	if _u.mutation.LastRefreshErrorCleared() {
		_spec.ClearField(balancesite.FieldLastRefreshError, field.TypeString)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancesite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceSiteUpdateOne is the builder for updating a single BalanceSite entity.
type BalanceSiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceSiteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceSiteUpdateOne) SetUpdatedAt(v time.Time) *BalanceSiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *BalanceSiteUpdateOne) SetPlatform(v balancesite.Platform) *BalanceSiteUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillablePlatform(v *balancesite.Platform) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *BalanceSiteUpdateOne) SetName(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableName(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *BalanceSiteUpdateOne) SetBaseURL(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableBaseURL(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *BalanceSiteUpdateOne) SetAuthMode(v balancesite.AuthMode) *BalanceSiteUpdateOne {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableAuthMode(v *balancesite.AuthMode) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *BalanceSiteUpdateOne) SetUsername(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableUsername(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *BalanceSiteUpdateOne) SetEmail(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableEmail(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *BalanceSiteUpdateOne) SetPasswordEncrypted(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillablePasswordEncrypted(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_u *BalanceSiteUpdateOne) SetAccessTokenEncrypted(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetAccessTokenEncrypted(v)
	return _u
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableAccessTokenEncrypted(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetAccessTokenEncrypted(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BalanceSiteUpdateOne) SetEnabled(v bool) *BalanceSiteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableEnabled(v *bool) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *BalanceSiteUpdateOne) SetRefreshIntervalMinutes(v int) *BalanceSiteUpdateOne {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableRefreshIntervalMinutes(v *int) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *BalanceSiteUpdateOne) AddRefreshIntervalMinutes(v int) *BalanceSiteUpdateOne {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *BalanceSiteUpdateOne) SetLastRefreshAt(v time.Time) *BalanceSiteUpdateOne {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableLastRefreshAt(v *time.Time) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *BalanceSiteUpdateOne) ClearLastRefreshAt() *BalanceSiteUpdateOne {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (_u *BalanceSiteUpdateOne) SetLastRefreshStatus(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetLastRefreshStatus(v)
	return _u
}

// SetNillableLastRefreshStatus sets the "last_refresh_status" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableLastRefreshStatus(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetLastRefreshStatus(*v)
	}
	return _u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_u *BalanceSiteUpdateOne) SetLastRefreshError(v string) *BalanceSiteUpdateOne {
	_u.mutation.SetLastRefreshError(v)
	return _u
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_u *BalanceSiteUpdateOne) SetNillableLastRefreshError(v *string) *BalanceSiteUpdateOne {
	if v != nil {
		_u.SetLastRefreshError(*v)
	}
	return _u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (_u *BalanceSiteUpdateOne) ClearLastRefreshError() *BalanceSiteUpdateOne {
	_u.mutation.ClearLastRefreshError()
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the BalanceKeySnapshot entity by IDs.
func (_u *BalanceSiteUpdateOne) AddSnapshotIDs(ids ...int64) *BalanceSiteUpdateOne {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the BalanceKeySnapshot entity.
func (_u *BalanceSiteUpdateOne) AddSnapshots(v ...*BalanceKeySnapshot) *BalanceSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddBindingIDs adds the "bindings" edge to the AccountBalanceBinding entity by IDs.
func (_u *BalanceSiteUpdateOne) AddBindingIDs(ids ...int64) *BalanceSiteUpdateOne {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the AccountBalanceBinding entity.
func (_u *BalanceSiteUpdateOne) AddBindings(v ...*AccountBalanceBinding) *BalanceSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the BalanceSiteMutation object of the builder.
func (_u *BalanceSiteUpdateOne) Mutation() *BalanceSiteMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the BalanceKeySnapshot entity.
func (_u *BalanceSiteUpdateOne) ClearSnapshots() *BalanceSiteUpdateOne {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to BalanceKeySnapshot entities by IDs.
func (_u *BalanceSiteUpdateOne) RemoveSnapshotIDs(ids ...int64) *BalanceSiteUpdateOne {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to BalanceKeySnapshot entities.
func (_u *BalanceSiteUpdateOne) RemoveSnapshots(v ...*BalanceKeySnapshot) *BalanceSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearBindings clears all "bindings" edges to the AccountBalanceBinding entity.
func (_u *BalanceSiteUpdateOne) ClearBindings() *BalanceSiteUpdateOne {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to AccountBalanceBinding entities by IDs.
func (_u *BalanceSiteUpdateOne) RemoveBindingIDs(ids ...int64) *BalanceSiteUpdateOne {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to AccountBalanceBinding entities.
func (_u *BalanceSiteUpdateOne) RemoveBindings(v ...*AccountBalanceBinding) *BalanceSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Where appends a list predicates to the BalanceSiteUpdate builder.
func (_u *BalanceSiteUpdateOne) Where(ps ...predicate.BalanceSite) *BalanceSiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceSiteUpdateOne) Select(field string, fields ...string) *BalanceSiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceSite entity.
func (_u *BalanceSiteUpdateOne) Save(ctx context.Context) (*BalanceSite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceSiteUpdateOne) SaveX(ctx context.Context) *BalanceSite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceSiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceSiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceSiteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancesite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceSiteUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := balancesite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := balancesite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := balancesite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := balancesite.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := balancesite.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := balancesite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		if err := balancesite.RefreshIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "refresh_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.refresh_interval_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastRefreshStatus(); ok {
		if err := balancesite.LastRefreshStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_refresh_status", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.last_refresh_status": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceSiteUpdateOne) sqlSave(ctx context.Context) (_node *BalanceSite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancesite.Table, balancesite.Columns, sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceSite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancesite.FieldID)
		for _, f := range fields {
			if !balancesite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancesite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancesite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(balancesite.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balancesite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(balancesite.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(balancesite.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(balancesite.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(balancesite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(balancesite.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(balancesite.FieldAccessTokenEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(balancesite.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(balancesite.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(balancesite.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(balancesite.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(balancesite.FieldLastRefreshAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshStatus(); ok {
		_spec.SetField(balancesite.FieldLastRefreshStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRefreshError(); ok {
		_spec.SetField(balancesite.FieldLastRefreshError, field.TypeString, value)
	}
	if _u.mutation.LastRefreshErrorCleared() {
		_spec.ClearField(balancesite.FieldLastRefreshError, field.TypeString)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceSite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancesite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
