// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountbalancebinding"
	"github.com/Wei-Shaw/sub2api/ent/balancekeysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
)

// BalanceSiteCreate is the builder for creating a BalanceSite entity.
type BalanceSiteCreate struct {
	config
	mutation *BalanceSiteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceSiteCreate) SetCreatedAt(v time.Time) *BalanceSiteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableCreatedAt(v *time.Time) *BalanceSiteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalanceSiteCreate) SetUpdatedAt(v time.Time) *BalanceSiteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableUpdatedAt(v *time.Time) *BalanceSiteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *BalanceSiteCreate) SetPlatform(v balancesite.Platform) *BalanceSiteCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BalanceSiteCreate) SetName(v string) *BalanceSiteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *BalanceSiteCreate) SetBaseURL(v string) *BalanceSiteCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *BalanceSiteCreate) SetUsername(v string) *BalanceSiteCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableUsername(v *string) *BalanceSiteCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *BalanceSiteCreate) SetEmail(v string) *BalanceSiteCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableEmail(v *string) *BalanceSiteCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_c *BalanceSiteCreate) SetPasswordEncrypted(v string) *BalanceSiteCreate {
	_c.mutation.SetPasswordEncrypted(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BalanceSiteCreate) SetEnabled(v bool) *BalanceSiteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableEnabled(v *bool) *BalanceSiteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_c *BalanceSiteCreate) SetRefreshIntervalMinutes(v int) *BalanceSiteCreate {
	_c.mutation.SetRefreshIntervalMinutes(v)
	return _c
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableRefreshIntervalMinutes(v *int) *BalanceSiteCreate {
	if v != nil {
		_c.SetRefreshIntervalMinutes(*v)
	}
	return _c
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_c *BalanceSiteCreate) SetLastRefreshAt(v time.Time) *BalanceSiteCreate {
	_c.mutation.SetLastRefreshAt(v)
	return _c
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableLastRefreshAt(v *time.Time) *BalanceSiteCreate {
	if v != nil {
		_c.SetLastRefreshAt(*v)
	}
	return _c
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (_c *BalanceSiteCreate) SetLastRefreshStatus(v string) *BalanceSiteCreate {
	_c.mutation.SetLastRefreshStatus(v)
	return _c
}

// SetNillableLastRefreshStatus sets the "last_refresh_status" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableLastRefreshStatus(v *string) *BalanceSiteCreate {
	if v != nil {
		_c.SetLastRefreshStatus(*v)
	}
	return _c
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_c *BalanceSiteCreate) SetLastRefreshError(v string) *BalanceSiteCreate {
	_c.mutation.SetLastRefreshError(v)
	return _c
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_c *BalanceSiteCreate) SetNillableLastRefreshError(v *string) *BalanceSiteCreate {
	if v != nil {
		_c.SetLastRefreshError(*v)
	}
	return _c
}

// AddSnapshotIDs adds the "snapshots" edge to the BalanceKeySnapshot entity by IDs.
func (_c *BalanceSiteCreate) AddSnapshotIDs(ids ...int64) *BalanceSiteCreate {
	_c.mutation.AddSnapshotIDs(ids...)
	return _c
}

// AddSnapshots adds the "snapshots" edges to the BalanceKeySnapshot entity.
func (_c *BalanceSiteCreate) AddSnapshots(v ...*BalanceKeySnapshot) *BalanceSiteCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapshotIDs(ids...)
}

// AddBindingIDs adds the "bindings" edge to the AccountBalanceBinding entity by IDs.
func (_c *BalanceSiteCreate) AddBindingIDs(ids ...int64) *BalanceSiteCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the AccountBalanceBinding entity.
func (_c *BalanceSiteCreate) AddBindings(v ...*AccountBalanceBinding) *BalanceSiteCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// Mutation returns the BalanceSiteMutation object of the builder.
func (_c *BalanceSiteCreate) Mutation() *BalanceSiteMutation {
	return _c.mutation
}

// Save creates the BalanceSite in the database.
func (_c *BalanceSiteCreate) Save(ctx context.Context) (*BalanceSite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceSiteCreate) SaveX(ctx context.Context) *BalanceSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceSiteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balancesite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := balancesite.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := balancesite.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := balancesite.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := balancesite.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RefreshIntervalMinutes(); !ok {
		v := balancesite.DefaultRefreshIntervalMinutes
		_c.mutation.SetRefreshIntervalMinutes(v)
	}
	if _, ok := _c.mutation.LastRefreshStatus(); !ok {
		v := balancesite.DefaultLastRefreshStatus
		_c.mutation.SetLastRefreshStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceSiteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalanceSite.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BalanceSite.updated_at"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "BalanceSite.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := balancesite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BalanceSite.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := balancesite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "BalanceSite.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := balancesite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "BalanceSite.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := balancesite.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "BalanceSite.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := balancesite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordEncrypted(); !ok {
		return &ValidationError{Name: "password_encrypted", err: errors.New(`ent: missing required field "BalanceSite.password_encrypted"`)}
	}
	if v, ok := _c.mutation.PasswordEncrypted(); ok {
		if err := balancesite.PasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "password_encrypted", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.password_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "BalanceSite.enabled"`)}
	}
	if _, ok := _c.mutation.RefreshIntervalMinutes(); !ok {
		return &ValidationError{Name: "refresh_interval_minutes", err: errors.New(`ent: missing required field "BalanceSite.refresh_interval_minutes"`)}
	}
	if v, ok := _c.mutation.RefreshIntervalMinutes(); ok {
		if err := balancesite.RefreshIntervalMinutesValidator(v); err != nil {
			return &ValidationError{Name: "refresh_interval_minutes", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.refresh_interval_minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastRefreshStatus(); !ok {
		return &ValidationError{Name: "last_refresh_status", err: errors.New(`ent: missing required field "BalanceSite.last_refresh_status"`)}
	}
	if v, ok := _c.mutation.LastRefreshStatus(); ok {
		if err := balancesite.LastRefreshStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_refresh_status", err: fmt.Errorf(`ent: validator failed for field "BalanceSite.last_refresh_status": %w`, err)}
		}
	}
	return nil
}

func (_c *BalanceSiteCreate) sqlSave(ctx context.Context) (*BalanceSite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceSiteCreate) createSpec() (*BalanceSite, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceSite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancesite.Table, sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balancesite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balancesite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(balancesite.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(balancesite.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(balancesite.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(balancesite.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(balancesite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordEncrypted(); ok {
		_spec.SetField(balancesite.FieldPasswordEncrypted, field.TypeString, value)
		_node.PasswordEncrypted = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(balancesite.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(balancesite.FieldRefreshIntervalMinutes, field.TypeInt, value)
		_node.RefreshIntervalMinutes = value
	}
	if value, ok := _c.mutation.LastRefreshAt(); ok {
		_spec.SetField(balancesite.FieldLastRefreshAt, field.TypeTime, value)
		_node.LastRefreshAt = &value
	}
	if value, ok := _c.mutation.LastRefreshStatus(); ok {
		_spec.SetField(balancesite.FieldLastRefreshStatus, field.TypeString, value)
		_node.LastRefreshStatus = value
	}
	if value, ok := _c.mutation.LastRefreshError(); ok {
		_spec.SetField(balancesite.FieldLastRefreshError, field.TypeString, value)
		_node.LastRefreshError = &value
	}
	if nodes := _c.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.SnapshotsTable,
			Columns: []string{balancesite.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancekeysnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   balancesite.BindingsTable,
			Columns: []string{balancesite.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountbalancebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSite.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSiteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSiteCreate) OnConflict(opts ...sql.ConflictOption) *BalanceSiteUpsertOne {
	_c.conflict = opts
	return &BalanceSiteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSiteCreate) OnConflictColumns(columns ...string) *BalanceSiteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSiteUpsertOne{
		create: _c,
	}
}

type (
	// BalanceSiteUpsertOne is the builder for "upsert"-ing
	//  one BalanceSite node.
	BalanceSiteUpsertOne struct {
		create *BalanceSiteCreate
	}

	// BalanceSiteUpsert is the "OnConflict" setter.
	BalanceSiteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceSiteUpsert) SetUpdatedAt(v time.Time) *BalanceSiteUpsert {
	u.Set(balancesite.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateUpdatedAt() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldUpdatedAt)
	return u
}

// SetPlatform sets the "platform" field.
func (u *BalanceSiteUpsert) SetPlatform(v balancesite.Platform) *BalanceSiteUpsert {
	u.Set(balancesite.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdatePlatform() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldPlatform)
	return u
}

// SetName sets the "name" field.
func (u *BalanceSiteUpsert) SetName(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateName() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *BalanceSiteUpsert) SetBaseURL(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateBaseURL() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldBaseURL)
	return u
}

// SetUsername sets the "username" field.
func (u *BalanceSiteUpsert) SetUsername(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateUsername() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldUsername)
	return u
}

// SetEmail sets the "email" field.
func (u *BalanceSiteUpsert) SetEmail(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateEmail() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldEmail)
	return u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *BalanceSiteUpsert) SetPasswordEncrypted(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldPasswordEncrypted, v)
	return u
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdatePasswordEncrypted() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldPasswordEncrypted)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *BalanceSiteUpsert) SetEnabled(v bool) *BalanceSiteUpsert {
	u.Set(balancesite.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateEnabled() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldEnabled)
	return u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsert) SetRefreshIntervalMinutes(v int) *BalanceSiteUpsert {
	u.Set(balancesite.FieldRefreshIntervalMinutes, v)
	return u
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateRefreshIntervalMinutes() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldRefreshIntervalMinutes)
	return u
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsert) AddRefreshIntervalMinutes(v int) *BalanceSiteUpsert {
	u.Add(balancesite.FieldRefreshIntervalMinutes, v)
	return u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *BalanceSiteUpsert) SetLastRefreshAt(v time.Time) *BalanceSiteUpsert {
	u.Set(balancesite.FieldLastRefreshAt, v)
	return u
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateLastRefreshAt() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldLastRefreshAt)
	return u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *BalanceSiteUpsert) ClearLastRefreshAt() *BalanceSiteUpsert {
	u.SetNull(balancesite.FieldLastRefreshAt)
	return u
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (u *BalanceSiteUpsert) SetLastRefreshStatus(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldLastRefreshStatus, v)
	return u
}

// UpdateLastRefreshStatus sets the "last_refresh_status" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateLastRefreshStatus() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldLastRefreshStatus)
	return u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *BalanceSiteUpsert) SetLastRefreshError(v string) *BalanceSiteUpsert {
	u.Set(balancesite.FieldLastRefreshError, v)
	return u
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *BalanceSiteUpsert) UpdateLastRefreshError() *BalanceSiteUpsert {
	u.SetExcluded(balancesite.FieldLastRefreshError)
	return u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *BalanceSiteUpsert) ClearLastRefreshError() *BalanceSiteUpsert {
	u.SetNull(balancesite.FieldLastRefreshError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSiteUpsertOne) UpdateNewValues() *BalanceSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balancesite.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceSiteUpsertOne) Ignore() *BalanceSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSiteUpsertOne) DoNothing() *BalanceSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSiteCreate.OnConflict
// documentation for more info.
func (u *BalanceSiteUpsertOne) Update(set func(*BalanceSiteUpsert)) *BalanceSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceSiteUpsertOne) SetUpdatedAt(v time.Time) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateUpdatedAt() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatform sets the "platform" field.
func (u *BalanceSiteUpsertOne) SetPlatform(v balancesite.Platform) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdatePlatform() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdatePlatform()
	})
}

// SetName sets the "name" field.
func (u *BalanceSiteUpsertOne) SetName(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateName() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *BalanceSiteUpsertOne) SetBaseURL(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateBaseURL() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateBaseURL()
	})
}

// SetUsername sets the "username" field.
func (u *BalanceSiteUpsertOne) SetUsername(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateUsername() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateUsername()
	})
}

// SetEmail sets the "email" field.
func (u *BalanceSiteUpsertOne) SetEmail(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateEmail() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *BalanceSiteUpsertOne) SetPasswordEncrypted(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdatePasswordEncrypted() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BalanceSiteUpsertOne) SetEnabled(v bool) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateEnabled() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateEnabled()
	})
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsertOne) SetRefreshIntervalMinutes(v int) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetRefreshIntervalMinutes(v)
	})
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsertOne) AddRefreshIntervalMinutes(v int) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.AddRefreshIntervalMinutes(v)
	})
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateRefreshIntervalMinutes() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateRefreshIntervalMinutes()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *BalanceSiteUpsertOne) SetLastRefreshAt(v time.Time) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateLastRefreshAt() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *BalanceSiteUpsertOne) ClearLastRefreshAt() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.ClearLastRefreshAt()
	})
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (u *BalanceSiteUpsertOne) SetLastRefreshStatus(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshStatus(v)
	})
}

// UpdateLastRefreshStatus sets the "last_refresh_status" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateLastRefreshStatus() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshStatus()
	})
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *BalanceSiteUpsertOne) SetLastRefreshError(v string) *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshError(v)
	})
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *BalanceSiteUpsertOne) UpdateLastRefreshError() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshError()
	})
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *BalanceSiteUpsertOne) ClearLastRefreshError() *BalanceSiteUpsertOne {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.ClearLastRefreshError()
	})
}

// Exec executes the query.
func (u *BalanceSiteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSiteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSiteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceSiteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceSiteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceSiteCreateBulk is the builder for creating many BalanceSite entities in bulk.
type BalanceSiteCreateBulk struct {
	config
	err      error
	builders []*BalanceSiteCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceSite entities in the database.
func (_c *BalanceSiteCreateBulk) Save(ctx context.Context) ([]*BalanceSite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceSite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceSiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceSiteCreateBulk) SaveX(ctx context.Context) []*BalanceSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSite.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSiteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSiteCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceSiteUpsertBulk {
	_c.conflict = opts
	return &BalanceSiteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSiteCreateBulk) OnConflictColumns(columns ...string) *BalanceSiteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSiteUpsertBulk{
		create: _c,
	}
}

// BalanceSiteUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceSite nodes.
type BalanceSiteUpsertBulk struct {
	create *BalanceSiteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSiteUpsertBulk) UpdateNewValues() *BalanceSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balancesite.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSite.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceSiteUpsertBulk) Ignore() *BalanceSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSiteUpsertBulk) DoNothing() *BalanceSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSiteCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceSiteUpsertBulk) Update(set func(*BalanceSiteUpsert)) *BalanceSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceSiteUpsertBulk) SetUpdatedAt(v time.Time) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateUpdatedAt() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatform sets the "platform" field.
func (u *BalanceSiteUpsertBulk) SetPlatform(v balancesite.Platform) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdatePlatform() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdatePlatform()
	})
}

// SetName sets the "name" field.
func (u *BalanceSiteUpsertBulk) SetName(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateName() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *BalanceSiteUpsertBulk) SetBaseURL(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateBaseURL() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateBaseURL()
	})
}

// SetUsername sets the "username" field.
func (u *BalanceSiteUpsertBulk) SetUsername(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateUsername() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateUsername()
	})
}

// SetEmail sets the "email" field.
func (u *BalanceSiteUpsertBulk) SetEmail(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateEmail() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *BalanceSiteUpsertBulk) SetPasswordEncrypted(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdatePasswordEncrypted() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BalanceSiteUpsertBulk) SetEnabled(v bool) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateEnabled() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateEnabled()
	})
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsertBulk) SetRefreshIntervalMinutes(v int) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetRefreshIntervalMinutes(v)
	})
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *BalanceSiteUpsertBulk) AddRefreshIntervalMinutes(v int) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.AddRefreshIntervalMinutes(v)
	})
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateRefreshIntervalMinutes() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateRefreshIntervalMinutes()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *BalanceSiteUpsertBulk) SetLastRefreshAt(v time.Time) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateLastRefreshAt() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *BalanceSiteUpsertBulk) ClearLastRefreshAt() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.ClearLastRefreshAt()
	})
}

// SetLastRefreshStatus sets the "last_refresh_status" field.
func (u *BalanceSiteUpsertBulk) SetLastRefreshStatus(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshStatus(v)
	})
}

// UpdateLastRefreshStatus sets the "last_refresh_status" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateLastRefreshStatus() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshStatus()
	})
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *BalanceSiteUpsertBulk) SetLastRefreshError(v string) *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.SetLastRefreshError(v)
	})
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *BalanceSiteUpsertBulk) UpdateLastRefreshError() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.UpdateLastRefreshError()
	})
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *BalanceSiteUpsertBulk) ClearLastRefreshError() *BalanceSiteUpsertBulk {
	return u.Update(func(s *BalanceSiteUpsert) {
		s.ClearLastRefreshError()
	})
}

// Exec executes the query.
func (u *BalanceSiteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceSiteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSiteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSiteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
