// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancesite"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceSiteDelete is the builder for deleting a BalanceSite entity.
type BalanceSiteDelete struct {
	config
	hooks    []Hook
	mutation *BalanceSiteMutation
}

// Where appends a list predicates to the BalanceSiteDelete builder.
func (_d *BalanceSiteDelete) Where(ps ...predicate.BalanceSite) *BalanceSiteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BalanceSiteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceSiteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BalanceSiteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(balancesite.Table, sqlgraph.NewFieldSpec(balancesite.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BalanceSiteDeleteOne is the builder for deleting a single BalanceSite entity.
type BalanceSiteDeleteOne struct {
	_d *BalanceSiteDelete
}

// Where appends a list predicates to the BalanceSiteDelete builder.
func (_d *BalanceSiteDeleteOne) Where(ps ...predicate.BalanceSite) *BalanceSiteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BalanceSiteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{balancesite.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceSiteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
