// Code generated by ent, DO NOT EDIT.

package accountupstreammonitorrate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountupstreammonitorrate type in the database.
	Label = "account_upstream_monitor_rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldRateKey holds the string denoting the rate_key field in the database.
	FieldRateKey = "rate_key"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRatio holds the string denoting the ratio field in the database.
	FieldRatio = "ratio"
	// FieldCompletionRatio holds the string denoting the completion_ratio field in the database.
	FieldCompletionRatio = "completion_ratio"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// Table holds the table name of the accountupstreammonitorrate in the database.
	Table = "account_upstream_monitor_rates"
)

// Columns holds all SQL columns for accountupstreammonitorrate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldProvider,
	FieldRateKey,
	FieldDisplayName,
	FieldDescription,
	FieldRatio,
	FieldCompletionRatio,
	FieldFirstSeenAt,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RateKeyValidator is a validator for the "rate_key" field. It is called by the builders before save.
	RateKeyValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
)

// Provider defines the type for the "provider" enum field.
type Provider string

// ProviderSub2api is the default value of the Provider enum.
const DefaultProvider = ProviderSub2api

// Provider values.
const (
	ProviderSub2api Provider = "sub2api"
	ProviderNewapi  Provider = "newapi"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderSub2api, ProviderNewapi:
		return nil
	default:
		return fmt.Errorf("accountupstreammonitorrate: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the AccountUpstreamMonitorRate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByRateKey orders the results by the rate_key field.
func ByRateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateKey, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRatio orders the results by the ratio field.
func ByRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatio, opts...).ToFunc()
}

// ByCompletionRatio orders the results by the completion_ratio field.
func ByCompletionRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionRatio, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}
