// Code generated by ent, DO NOT EDIT.

package balancekeysnapshot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the balancekeysnapshot type in the database.
	Label = "balance_key_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldExternalKeyID holds the string denoting the external_key_id field in the database.
	FieldExternalKeyID = "external_key_id"
	// FieldMaskedKey holds the string denoting the masked_key field in the database.
	FieldMaskedKey = "masked_key"
	// FieldKeyLast4 holds the string denoting the key_last4 field in the database.
	FieldKeyLast4 = "key_last4"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldMatchStatus holds the string denoting the match_status field in the database.
	FieldMatchStatus = "match_status"
	// FieldKeyName holds the string denoting the key_name field in the database.
	FieldKeyName = "key_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldAccountBalance holds the string denoting the account_balance field in the database.
	FieldAccountBalance = "account_balance"
	// FieldSubscriptionBalance holds the string denoting the subscription_balance field in the database.
	FieldSubscriptionBalance = "subscription_balance"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldFetchedAt holds the string denoting the fetched_at field in the database.
	FieldFetchedAt = "fetched_at"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the balancekeysnapshot in the database.
	Table = "balance_key_snapshots"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "balance_key_snapshots"
	// SiteInverseTable is the table name for the BalanceSite entity.
	// It exists in this package in order to avoid circular dependency with the "balancesite" package.
	SiteInverseTable = "balance_sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "balance_key_snapshots"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for balancekeysnapshot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSiteID,
	FieldExternalKeyID,
	FieldMaskedKey,
	FieldKeyLast4,
	FieldAccountID,
	FieldMatchStatus,
	FieldKeyName,
	FieldStatus,
	FieldGroupID,
	FieldGroupName,
	FieldBalance,
	FieldAccountBalance,
	FieldSubscriptionBalance,
	FieldRateMultiplier,
	FieldFetchedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultExternalKeyID holds the default value on creation for the "external_key_id" field.
	DefaultExternalKeyID string
	// ExternalKeyIDValidator is a validator for the "external_key_id" field. It is called by the builders before save.
	ExternalKeyIDValidator func(string) error
	// DefaultMaskedKey holds the default value on creation for the "masked_key" field.
	DefaultMaskedKey string
	// MaskedKeyValidator is a validator for the "masked_key" field. It is called by the builders before save.
	MaskedKeyValidator func(string) error
	// DefaultKeyLast4 holds the default value on creation for the "key_last4" field.
	DefaultKeyLast4 string
	// KeyLast4Validator is a validator for the "key_last4" field. It is called by the builders before save.
	KeyLast4Validator func(string) error
	// DefaultKeyName holds the default value on creation for the "key_name" field.
	DefaultKeyName string
	// KeyNameValidator is a validator for the "key_name" field. It is called by the builders before save.
	KeyNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultGroupID holds the default value on creation for the "group_id" field.
	DefaultGroupID string
	// GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	GroupIDValidator func(string) error
	// DefaultGroupName holds the default value on creation for the "group_name" field.
	DefaultGroupName string
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance func() map[string]interface{}
	// DefaultAccountBalance holds the default value on creation for the "account_balance" field.
	DefaultAccountBalance func() map[string]interface{}
	// DefaultSubscriptionBalance holds the default value on creation for the "subscription_balance" field.
	DefaultSubscriptionBalance func() map[string]interface{}
)

// MatchStatus defines the type for the "match_status" enum field.
type MatchStatus string

// MatchStatusUnmatched is the default value of the MatchStatus enum.
const DefaultMatchStatus = MatchStatusUnmatched

// MatchStatus values.
const (
	MatchStatusUnmatched MatchStatus = "unmatched"
	MatchStatusMatched   MatchStatus = "matched"
	MatchStatusAmbiguous MatchStatus = "ambiguous"
	MatchStatusManual    MatchStatus = "manual"
)

func (ms MatchStatus) String() string {
	return string(ms)
}

// MatchStatusValidator is a validator for the "match_status" field enum values. It is called by the builders before save.
func MatchStatusValidator(ms MatchStatus) error {
	switch ms {
	case MatchStatusUnmatched, MatchStatusMatched, MatchStatusAmbiguous, MatchStatusManual:
		return nil
	default:
		return fmt.Errorf("balancekeysnapshot: invalid enum value for match_status field: %q", ms)
	}
}

// OrderOption defines the ordering options for the BalanceKeySnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySiteID orders the results by the site_id field.
func BySiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteID, opts...).ToFunc()
}

// ByExternalKeyID orders the results by the external_key_id field.
func ByExternalKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalKeyID, opts...).ToFunc()
}

// ByMaskedKey orders the results by the masked_key field.
func ByMaskedKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaskedKey, opts...).ToFunc()
}

// ByKeyLast4 orders the results by the key_last4 field.
func ByKeyLast4(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyLast4, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByMatchStatus orders the results by the match_status field.
func ByMatchStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchStatus, opts...).ToFunc()
}

// ByKeyName orders the results by the key_name field.
func ByKeyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByFetchedAt orders the results by the fetched_at field.
func ByFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFetchedAt, opts...).ToFunc()
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SiteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
